### ISSUE TITLE
Develop COMPOST brand

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#1]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Complete refresh of distributed.press and COMPOST.digital.   

## Task Summary

(Re)Launch both websites before summer events.

## To Do

- [x] COMPOST.digital domain -> @benhylau 
- [x] Website content -> copy out the hackmd for @maisutton to revise
- [x] Publish on Hypercore -> @benhylau `hyper://471cc39972548c64395b86bd3b48d1c5cdafe171a5e9a63ecd61f998e12529be`
- [x] Web content/copy, colour palette, wordmark -> @maisutton to work with Hanami, @uditvira 
  - e.g. https://handbook.hypha.coop/look-and-feel.html
  - Talk to 56.digital?
- [x] Website refresh -> @benhylau 
- [x] Add embedded mailing list form (see [guide](https://wiki.list.org/DOC/4.33%20How%20do%20I%20put%20a%20subscribe%20form%20for%20my%20list%20on%20a%20web%20page%3F))

**Comment by benhylau** [comment]
Hey @maisutton pls edit the website copy here https://hackmd.io/Yi9AXQFiRB2sCsUKv6PqBQ?view

**Comment by benhylau** [comment]
Current ideas of websites:

## Website layout (Distributed.Press)

### https://distributed.press
- On landing page, have a call out: "We're launching COMPOST. A magazine about ... Read more about it here!"
- Followed by existing Vision copy

### https://distributed.press/approach/
- Phase 1 (interviews and acknowledgements)
- Phase 2 (COMPOST and link to COMPOST domain)

### https://distributed.press/values/
- Leave as is

### Website for COMPOST.?
- One pager

**Comment by maisutton** [comment]
@benhylau Made a new version of the distributed.press homepage text here:
https://hackmd.io/Yi9AXQFiRB2sCsUKv6PqBQ?view

Did we decide to keep everything below Vision the same? I thought we wanted to revamp this all because we refined our project pitch so much for GFTW. I took the app language and condensed it, while making it a bit more informal.

Also drafted here because I sadly find Gdocs easier to edit in: https://docs.google.com/document/d/18-E0sjyjGbNjyjGRXkWr5E-YCMEYMhMHWdMxLB-xvH8/edit#heading=h.pmsa7200rbk

**Comment by benhylau** [comment]
Once we get a wordmark, I would like the following assets which are needed in our current theme:
- android-chrome-192x192.png
- apple-touch-icon.png
- favicon-32x32.png
- favicon-96x96.png
- mstile-310x310.png

For example, [this](https://github.com/hyphacoop/distributed.press/blob/master/favicon-96x96.png), which we currently use the asset associated with the theme. We should generate our own, for both Distributed Press and COMPOST.

**Comment by benhylau** [comment]
@maisutton I have updated https://distributed.press with `DISTRIBUTED.PRESS PAGE 2.0` section in the hackmd, with slight modification to this paragraph (updated in hackmd as well):

>*We’re soon launching [COMPOST](https://compost.digital), a magazine about the digital commons, telling stories about people building the Internet as a shared resource. The new site is coming soon so stay tuned!*

I like the flow and focus of the current copy 👍 

When the `Approach` section is ready, pls ping @uditvira to update [this page](https://github.com/hyphacoop/distributed.press/blob/master/approach.md). It's a standard merge to publish jekyll flow.

**Comment by benhylau** [comment]
Published COMPOST site at https://compost.digital based on hackmd text with slight modifications. Mainly changing Internet to web and some other text in this section:

>We’re creating **COMPOST**, a magazine about the digital commons that provides fertile ground for creative experimentation, cultivates communities that value participation, and celebrates the labor of regeneration and care. We are also building the Distributed Press tool for COMPOST, so that anyone can publish to the World Wide Web and Distributed Web.

and title formating/consistency changes only.

The copy on the site is the text taken from the hackmd, between `===COMPOST.digital START===` to `===COMPOST.digital END===` tags. You can change the text [here](https://github.com/hyphacoop/compost.digital/blob/master/index.md).

Once we have a Twitter account from #4 we should update [this link](https://github.com/hyphacoop/compost.digital/blob/master/_config.yml#L94). The same `_config.yml` file contains the description and footer text, if you would like to make changes.

**Comment by benhylau** [comment]
Add links to COMPOST inspo https://www.are.na/compost/compost-inspo

**Comment by benhylau** [comment]
@maisutton I believe we still need to refresh this page's text to describe the two phases of the project https://distributed.press/approach/

**Comment by benhylau** [comment]
It's published on `hyper://471cc39972548c64395b86bd3b48d1c5cdafe171a5e9a63ecd61f998e12529be` and seeded from my server, which follows https://github.com/hyperspace-org/hyperspace and https://github.com/hyperspace-org/hyperdrive-service to configure.

Right now the font isn't working bc it tries to get it thru a `hyper://` link off of google fonts, which obv won't work. I will wait till we finish branding and put the new font as a local resource, then it'll be fine.

This is manually deployed and not yet integrated into CI. We need to set up our own seed server (maybe as a VM on Hypha VM) in order to make this work with CI. Bigger task.

**Comment by benhylau** [comment]
@benhylau to draft https://distributed.press/approach/ refresh

**Comment by benhylau** [comment]
We can add an embedded form like this to the site. Need some server setting change first.

<img width="729" alt="Screen Shot 2020-08-19 at 2 00 47 AM" src="https://user-images.githubusercontent.com/2261308/90577038-09a4ff00-e1c0-11ea-95f5-da495cf732ef.png">

**Comment by benhylau** [comment]
- @maisutton @uditvira select font
- @maisutton then @uditvira website approach page edits
- @uditvira prototype visuals on website
