### ISSUE TITLE
M3 initiating and planning

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#106]
We are taking from mid-December to mid-January (aprox) to scope M3 and develope a schedule for tasks and deliverables inside the milestone.

We have clear goals (ready for effort estimation, issuing and calendarizing) and a few doubtful features (we need to discuss wether we keep or drop them, prioritizing) 

**Clear goals:**
#103  
#102 
#104 

**Pending or doubtful:**

- [x] a. Deletion of posts, is possible? _ImDef asked about this_. It's issued here: https://github.com/hyphacoop/distributed-press-organizing/issues/159
- [x] b. Bringing older posts prior to the following of ther account, is possible? _Interesting from a usability POV._
- [x] c. Do we want to add metadata to images? / _It's a nice to have, only if we get the time_
- [x] d. #101 the “announcing new account” is vague and we need to define clearer scope before estimating effort / calendarize it
- [x] e. Mauve to write down their idea on “social reader” and we discuss it. See #102 
- [x] f. Decide on federating with Threads
- [x] Confirm that we are dropping this (was present in 1st document with FFDW): Content versioning. Distributed Press will officially support listing and fetching of specific versions of published content, along with API responses that it internally generates over time. _Mauve says it could be valuable to re-visit this on Milestone 4, related to verification features._
- [x] Confirm that we are dropping this (was present in 1st document with FFDW): Content storage redundancy. Sutty adopting the activestorage-ipfs Rails plugin into their infrastructure. Distributed Press will add support for remote pinning for both IPFS and Hypercore.

**M3 processes wishlist**
1. We'll do more calendarizing, having timelines, checking in periodically regarding the time-line.
2. We'll take more time in testing. We should test prototypes, to validate our decisions, not just ready-to-launch features. Ben + users?
3. We'll open issues for bugs, and follow the labels _Bug- Review needed - Testing - Ready..._
4. We'll include Sutty's work in one card in the Board, whit links to the 0xacab issues.
5. We'll have a new type of bi-weekly meeting for parallel goals: - business - organizational

![Image](https://github.com/hyphacoop/distributed-press-organizing/assets/113475467/e8b157e4-7818-4d35-b33d-aac24f381d71)

**Comment by RangerMauve** [comment]
Thank you for putting this together! V useful summary of the state of things.

**Comment by sutty-coop** [comment]
### Update from weekly meeting Jan 4th:

-  “announcing new account” was better defined. See details in [101 ](https://github.com/hyphacoop/distributed-press-organizing/issues/101)

- "bringing older posts prior to the following the account" was adressed. TO DO: @RangerMauve will find an issue re: "older posts not visible" and we'll continue from there. It's [here](https://github.com/hyphacoop/distributed-press-organizing/issues/156)

- "moderation queue in CMS" will be presented as a prototype before Jan 15th. Others can validate and give feedback.

- we'll add "workshops with communities" as a deliverable to M3

- deletion of posts to be scoped by Mauve, could Sutty implement?

**Comment by sutty-coop** [comment]
### Final step:
* Each team estimates work packages and times of completion
* Creates issues
* We work on a common calendar where we also consider tasks that include dependencies of Sutty)(Hypha
