### ISSUE TITLE
Workshops with communities

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#109]
📅 **Due date:** 03/31 
🎯 **Success criteria:** Reports with insights from each community, concrete use cases and UX input from communities sudacas

## Task Summary

...

## To Do

- [x] Define the methodology and activities for each workshop
- [x] Schedule at least 3 groups among communities, including grassroots activists, independent media journalists and workers, union activists, feminist and trans* and non binary activists who are able to commit to a virtual or physical workshop of 3 hours.
- [x] Run the workshops and process the insights from each of them
- [x] Write down a report

**Comment by sutty-coop** [comment]
- [x] The first workshop was run by the team with a group from Medios Libres, on Saturday 24th

- [x] The second workshop will happen with a group from SITRAJU

- [x] The third workshop will be run with workers from ImDefensoras

**Comment by sutty-coop** [comment]
Conclusions in April, reported in the Biannual Report:
We found out that we need to improve our time estimations when working with grassroots communities. These user communities face direct censorship or threats that may put their lives in danger, or deal with socio-political situations of crisis and uncertainty. In addition, in Argentina there was a dengue epidemic affecting team members and many persons from the communities. Scheduling workshops was troubling through this circumstances, resulting in delays, cancellations, rescheduling, etc.
The final report will be presented by april 24th

**Comment by sutty-coop** [comment]
PARTIAL REPORT v0.75


[Preliminary-partial_report__HHRR-Defenders-digital-co-care__202404.pdf](https://github.com/hyphacoop/distributed-press-organizing/files/15134219/Preliminary-partial_report__HHRR-Defenders-digital-co-care__202404.pdf)
