### ISSUE TITLE
Grant: Ethereum Foundation

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#11]
🎟️ **Re-ticketed from:** #6   
📅 **Due date:** Friday October 16, 2020
🎯 **Success criteria:** Submit application to EF Ecosystem Support

## Task Summary
- Completed 1.5 pager to EF
- Connect w/ EF and gotten feedback
- Submit for EF Ecosystem Support

## To Do

- [x] Draft 1.5 pager on project
- [x] Send to Scott Moore to review
- [x] Arrange meeting with EF to get feedback
- [x] Re-draft and send to EF
- [ ] Connect with Kelsey at Simply Secure
- [ ] Connect with Colin, maybe Juan, at Protocol Labs

**Comment by maisutton** [comment]
**Notes from meeting with Scott Moore of EF/Gitcoin**
October 2, 2020 1pm PT 
- Gitcoin
-- Distribution tech for $, democratic, uses quadratic funding scheme
-- Next is November round
-- Hasn't been many projects in the "community" theme
-- Last time $30K in matching
- First two rounds EF only matched, now they have other funding sources

- Ethereum Foundation Ecosystem Support
-- State clear impact/measurement: What will be the impact of the $?
-- Should be Ethereum-based (at least related)
-- Do it right first so there's an ongoing relationship
-- Make sure project doesn't get stuck in review limbo
-- Very likely $5K, likely $10-15K, below $30K
-- Scott's critique of Coil - Ripple-based, therefore too centralized?
-- Still good to see we've gotten GFTW support, still don't pitch too much on Coil aspect, it's about exploration and building better design patterns for DWeb social layer/support

- Pitch to Ken
-- How the tech supports sustainability for creators/developers
-- How to have more buy-in from community
-- How to do it with tokens possibly? <- not necessary
-- How is this project part of expanding the semantic web?

Two parts 
1) Community/content 
2) Publishing element -> decentralized social layer
