### ISSUE TITLE
Develop monetization flow

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#12]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Develop a monetization flow that includes receiving and distributing money on various platforms, areas of collective decision making and baseline UI.

## Task Summary

A cross-platform monetization pilot that allows real-time visibility into the magazine's revenue generation and allocation. This will also support a crowdfund that allows the community to unlock premium features / goals developed by the creators.

## To Do

- [x] Draft framework
- [x] Discuss with team
- [x] Identify areas for co-creation sessions
- [x] Draft technical roadmap
- [x] Create tasks for next steps

**Comment by benhylau** [comment]
Some early ideas

![IMG_20201018_004811_1_1](https://user-images.githubusercontent.com/2261308/96359124-05706180-10dd-11eb-861b-0dc214f25ade.jpg)
![IMG_20201018_004913_1_1](https://user-images.githubusercontent.com/2261308/96359125-0608f800-10dd-11eb-9196-7aeafa521eda.jpg)
![IMG_20201018_005206_1_1](https://user-images.githubusercontent.com/2261308/96359126-0608f800-10dd-11eb-9861-8e574dc87b91.jpg)

**Comment by benhylau** [comment]
After looking into the features supported by Web Monetization and Uphold, I propose the following UI and workflow.

The COMPOST UI will feature the following options for readers to support the magazine:

1. Make a contribution in fiat currencies
2. Make a contribution in cryptocurrencies
3. Make a contribution via Web Monetization

## 1. Make a contribution in fiat currencies

- Fetches https://api.distributed.press/v0/monetization/balances/compost to display current balance in CAD #15 (the fetch will be from ipns and hyper for dweb versions)
- Links to our [Open Collective account](opencollective.com/compost/)
- Description about our Open Collective and instructions to donate

## 2. Make a contribution in cryptocurrencies

- Fetches https://api.distributed.press/v0/monetization/balances/compost to display current balance in ETH and ERC20 tokens #15 (the fetch will be from ipns and hyper for dweb versions)
- Links to our [Gitcoin page](opencollective.com/compost/)
- Description about our Gitcoin and instructions to donate in ETH or any ERC20 tokens

## 3. Make a contribution via Web Monetization

- If someone is using a Web Monetization-enabled browser, we will display a real-time balance of how much we are receiving _from them_ (e.g. `0.000786823 XRP` updated every second) using the [micropayment counter](https://webmonetization.org/docs/counter)
- If someone is not using a Web Monetization-enabled browser, we display description about using Coil and Web Monetization. This message is hidden if they are already using Web Monetization and we can [detect like this](https://webmonetization.org/docs/remove-ads)
- COMPOST will have an Uphold account to receive Web Monetization from the Interledger Network, which will look like this:
    ![Screen Shot 2020-12-04 at 2 30 17 PM](https://user-images.githubusercontent.com/2261308/101208509-4c3ff980-3640-11eb-8191-cbe43eaea370.png)
    This screen is authenticated, so it is only accessible for the administrators of the magazine. Left column shows real-time transactions, periodically deposited into the accounts in the middle column (we will keep everything CAD). Then periodically we can do a wire transfer to the Canadian bank account and allocate the balance received to our Open Collective
- If authors have Uphold account themselves (need KYC), they can directly monetize by providing their payment pointers at time of publishing, using [probabilistic revenue sharing](https://webmonetization.org/docs/probabilistic-rev-sharing) in the magazine (this should be an Issue Two feature)

**Comment by bennlich** [comment]
When you make a contribution via web monetization, is that fiat or crypto? Do you get to choose? Or is it something else entirely?

Dropping a note that we will definitely want to make the amount YOU have contributed extremely distinct from the total amount compost has raised. Maybe even render that in a totally different place on the page.

**Comment by benhylau** [comment]
That's a good question, and I found that answer [here](https://webmonetization.org/docs/counter/) yesterday:

>The asset code describes the asset the Web Monetization receiver is denominating their incoming payments in. This often matches the currency your wallet account uses, but not always.

and in our case, it is XRP, even though my payment pointer is associated with a CAD or ETH account. So in Uphold, we are in the "but not always" category. This currency code will be proxied through the #15 API.

>Dropping a note that we will definitely want to make the amount YOU have contributed extremely visually distinct from the total amount compost has raised. Maybe even render that in a totally different place on the page.

Yes, we actually have no way of telling the total amount raised via web monetization in real-time unless we integrate with Uphold API (which I don't want to do bc it tightly couples us to a platform and puts a high barrier to set up an instance of Distributed Press, needing to be registered business account with Uphold and implement OAuth). This is why I prefer to have the _total amount raised_ be aggregated into Open Collective manually after some period of time. So the _real-time by you via Web Monetization_ amount is definitely visually distinct from that.

**Comment by bennlich** [comment]
@benhylau do we have a gitcoin page yet?

**Comment by uditvira** [comment]
> @benhylau do we have a gitcoin page yet?

I think you're looking for this: https://gitcoin.co/grants/1385/compost

**Comment by bennlich** [comment]
@benhylau @maisutton @uditvira Do any of you have thoughts about which pages of issue 1 should activate micropayment streaming? I could see any of these options:

1) every page (homepage, about page, piece pages, support us page, etc.)
raionale: simple to understand (if you're looking at anything at one.compost.digital, you're streaming money to us)
cons: if being in "a streaming money state" feels like pressure, people might feel rushed or surprised when they arrive at the homepage. I think the whole point is that it's invisible and you don't really care cause the amounts are so small though, so I kinda think this con is moot.

2) only piece pages
rationale: you're paying to read the magazine content, not the about page
cons: the about page is part of the magazine too. why not pay for that?

3) every page besides the home page
rationale: taking your money on the landing page feels too bold, even if it's pennies, but everything else is fair game

Aside: one thing that might be fun to do is make a special page appear in the table of contents for people who have web mon enabled

As far as UX goes, it seems like it is becoming semi-standard to show the web monetization icon somewhere kind of out of the way when streaming is happening. And it might also be nice to render a small "thank you!" message alongside it. @benhylau have you come across any examples of other web-monetized publications?

**Comment by benhylau** [comment]
Every page. (1). Remember you aren't exactly "taking money from the user". It gets paid out of Coil's global pool. Even if we don't web monetize the user pays same $5 each month. The whole point is for it to happen in the background, nobody has to think about it.
