### ISSUE TITLE
Establish relationship with crowdfunding platforms

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#13]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Initiate a relationship with each and set up necessary accounts on crowdfunding platforms.  

## Task Summary

We are hoping to crowdfund via three platforms/protocols:
- Web Monetization
- Gitcoin
- Open Collective

## To Do

- [x] Web Monetization (relationship via GFTW)
- [x] Gitcoin (https://gitcoin.co/grants/1385/compost with Scott)
- [x] Open Collective (https://github.com/hyphacoop/organizing/issues/336 with Alanna and hosted by [Hypha](https://opencollective.com/hyphacoopinc/))
