### ISSUE TITLE
Launch first issue Call for Proposal

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#14]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Nov 2020  
🎯 **Success criteria:** Publish Call for Proposal on website and advertise it through networks.  

## Task Summary

Call for Proposal for first issue.

## To Do

- [x] Draft copy
- [x] Publish on compost.digital
- [ ] Add illustrations
- [x] Share it with contact list
- [x] Announce it on social media
