### ISSUE TITLE
Prototype webmonetization payment

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#16]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Nov 25, 2020  
🎯 **Success criteria:** Create a static web page on WWW that supports web monetization.

## Task Summary

Publish a web monetized static web page using the tools available [here](https://webmonetization.org/).

## To Do

- [x] Evaluate Web Monetization Tools for publishing static websites such as [hugo](https://github.com/sabinebertram/hugo-webmonetization-component) or [gatsby](https://github.com/mrmuhammadali/gatsby-plugin-monetization)
- [x] Set up Web Monetization Wallet for testing such as [uphold](https://uphold.com) and [gatehub](https://gatehub.net/)
- [x] Connect wallet to a Web Monetization Enabled Browser such as [Puma](https://www.pumabrowser.com)
- [x] Load website and complete a web monetization transaction
- [x] Document test setup for one other member to reproduce
- [x] Do a demo at a meeting

**Comment by benhylau** [comment]
- Created a personal account `benhylau` on Coil with a USD 5/month subscription
- Created a personal Uphold account, verified account with driver's license and a selfie (almost instant verification)
- Created a personal GateHub account, but didn't proceed with account verification (similar ID requirements as Uphold) bc it seems to have [less bank connection and currency support compared to Upload](https://webmonetization.org/docs/ilp-wallets)

**Comment by benhylau** [comment]
## Web Monetization to an ETH address

In Uphold, we can create a payment pointer to an ETH address (instead of CAD) `$ilp.uphold.com/nZiM4UKFJjjb`. Using this pointer, it will web monetize to our Uphold account's ETH wallet `0x60Ce332C1D1aF71583D1139BC1e3de52B54025AF`.

![Screen Shot 2020-11-24 at 11 36 51 PM](https://user-images.githubusercontent.com/2261308/100184159-d654c900-2eae-11eb-9a54-339932da5684.png)

In theory, the ETH will go onto the Ethereum chain but it hasn't happened yet:
https://api.etherscan.io/api?module=account&action=balance&address=0x60Ce332C1D1aF71583D1139BC1e3de52B54025AF&tag=latest
