### ISSUE TITLE
Petr - Onboarding

### ISSUE THREAD

**Issue by pp2tech** [hyphacoop/distributed-press-organizing#165]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** aprox. 15-20th May
🎯 **Success criteria:** Can move to hyphotesis formulation step  

## Task Summary

...

## To Do 1st - MEET THE TEAM :)

- [x] Ben (DP idea father, now not involved daily)
- [x] Andi (our relationship holder)
- [x] Muave (tech lead - Sutty)
- [x] Fauno (prod.leaad - Sutty CMS)
- [x] Aki (the only DP full time dev)
- [x] Ania (comms, and ProjM)
- [x] UX Team (Sutty) - Elio, Edu, Dili
- [ ] ... ?

## To Dos to Understand Business Fundamentals

- [x]  Understand Hypha's and Sutty's overall vision, strategy and opportunities the teams are seeing now
- [x] Understand key company goals, metrics, KPIs / OKRs
- [x] Understand company financial models and available data
- [x] Understand competitive landscape and risks
- [x] Understand markets we do (and want to) play in
- - see the Miro board: https://miro.com/app/board/uXjVPK6r5i8=/?share_link_id=883778821563
- [x] Create or Review Positioning (internal) 
- - https://docs.google.com/document/d/1WAP8_IqMtRsuXiLBF5islr1h1QnX28OKVabe6V592QM/

- [x] Understand the opportunities pipeline (if exists) / what events are going to impact it in the next 90 days
 -- no immediate opportunities but at least some potentially relevant organizations are listed in doc that Ben started Opportunities: https://docs.google.com/document/d/1O9LxPjPRrQPD0Wrf3LZYUXTHzSWYg8M4E92feupSknI/edit#heading=h.fn243rnup9h7

## To Dos to Understand the Product deeply

- [x] Get full product access, work through tutorials (? if exist)
- [x] Understand product architecture
- n/a Any regular public product on-boarding webinars? (weekly/monthly)
- [x] Get in-depth product demos from respective PMs to understand the core value proposition

- [x] Get the feeling for the main customer problems that the product solves 
- - here is the issue, most people DP would like to target (journalists, collectives, etc.) like the idea but don't feel the problem, or they don't care about our solution at all

- [x] Understand the main product features and main product limitations // Are they intentional (strategy) vs genuine gaps? - N/A

- [x] Understand the product roadmap - what and why things are on the roadmap? 
- [x] Understand the product onboarding 💯 NUX (New User experience) from all onboarding paths // Friction points // Setup Moments // Aha moments -- N/A

## To Dos to Understand Customers from internal (Hypha/Sutty) point of view

- [x] Understand buyer and user personas
- - we will have to figure this out after narrowing down the focus of the DP offering

- [x] Understand customer journey (maybe a map exists?) - map does not exist (except basic Sutty's onboarding)
- [ ] Understand (or start creating) the Ideal Customer Profile(s) (ICP) // from Hypha's perspectivef and rom Sutty's perspective (and will probably need independent from product perspective) 
- - - we will have to figure this out after narrowing down the focus of the DP offering
- [x] Understand the JTBD. // Why are customers hiring DP ?
- - our assumption for next steps will be that "Customer hires DP to get the comprehensive distributed web/blockchain publishing capabilities from which she can pick&choose where to publish in addition to traditional web2 publishing." // The proposition can be adjusted for Sutty's B2B offering, where it will include CMS frontend. I assume B2C offering of Sutty is unchanged by new DP's direction. 

- [x] Understand what users most love about the product? - right now users mostly like the idea, not the product 
- [ ] Understand what users most wished the product could do for them 
- [x] Understand conversion friction - N/A
- [x] What stops customers from buying? - N/A
- [x] Why do customers churn? - N/A
- [x] What interviews have we done with churned customers? - N/A
- [x] Has anything proven effective in churned user resurrection? - N/A
- [x] Any surveys in place? - N/A
- [x] Messaging - from internal perspective = Do we feel we have message-market fit? - N/A
- [x] Is that language/message perpetuated throughout the product itself? - N/A
- [x] What are the best performing channels (organic & paid) and what channels were tried? - N/A
- [x] What paid channels were tried but didn’t create good ROI? - N/A

## To Dos to Understand Customer from customer side (by talking to them)

- [x] Participate in customer success calls (aka ride-along) // who's doing them? - N/A
- [x] Who knows the following answers - or has/should have informed opinion on it? -> What makes customers successful? // What best practices do customers employ? // Why do some customers not realise value from the product? // What are the biggest issues customers face? // What is the pitch? // What messaging works best?What is best avoided? - N/A

## To Dos to Understand available Product Metrics

- [ ] Get access to existing dashboards / check use cases - N/A

**- [ ] Get access to the full analytics - product, marketing, website - stack (or whatever exists) // I think someone mentioned Plausible ( https://plausible.io/) - does anything else exist (automated)?**

- [ ] DP API usage stats 
- [ ] DP website stats
- [ ] DP docs site stats

- [x] Understand data events and relevant guidelines // Structure, naming, level of abstraction etc...Is this shared and used across all teams consistently? -- N/A
- [x] Understand basic usage and retention metrics (or see what should/can exist and be created)
Global -- N/A, does not exists

- By new user signup cohort
- By type of account
- By type of company
- By activation event completion
- By frequency of specific activities
- Per feature
- By acquisition channel
- By new / resurrected userUnderstand the experience funnel and all stage conversion metrics

## To Dos to Understand Ways of Working (WOW) of product and other teams (what teams. exist?)

- [x] Understand product org KPIs / OKRs, process and tooling
- [x] Understand how the product and marketing teams are structured today
- [x] Org / reporting models + Ideas/ backlog management
- [x] Understand the model for any shared resources -> like usually Design? Data? Website? 
- [x] Understand the working methodology and cadence of work -> Sprint lengths? (Understand team velocities / tempos)
- [x] Understand the key meetings and get invitations 
- [x] Understand any established patterns / norms for communication/collaboration and documentation
