### ISSUE TITLE
Add migration script for p2p

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#168]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

It'd be useful to make a script to migrate folks on HTTP based ActivtyPub to our P2P spec

## To Do

- [ ] Register a distributed press token or use agregore-cli
- [ ] Create a new site
- [ ] Pull down actor/outbox/activities/notes/webfinger
- [ ] Convert to p2p actor with all the data but with new urls
- [ ] add HTTP versions of files which use a gateway
- [ ] add everything to the p2p site
- [ ] generate new keypair and register on social
- [ ] show user webfinger `@username@gateway-subdmain` string they can share with others to follow them.
- [ ] test on migrating mastodon
- [ ] provide cli for pulling incming messages from inbox
- [ ] provide cli for adding a new note
- [ ] fork reader to follow accounts and index your inbox

**Comment by fauno** [comment]
What about the Move action? Could we convert an Actor to a static website this way too?

**Comment by RangerMauve** [comment]
Yeah that'd need the ability to authenticate across implementations, though.
