### ISSUE TITLE
Ansible for Distributed Press

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#17]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Dec 4, 2020  
🎯 **Success criteria:** Publish Distributed Press Ansible that can pin/server content to WWW, Hypercore, and IPFS.

## Task Summary

Build an Ansible that will become the beginning of the Distributed Press. This server runs Hypercore, IPFS, and has WWW access, such that we can take a static website and pin/serve it on all three networks.

## To Do

- [x] Set up WWW server, publish content, and verify fetch on WWW browser
- [x] Set up Hypercore, publish content, and verify fetch from Beaker browser
- [x] Set up IPFS, publish content, and verify fetch from independent IPFS node
- [x] Publish Ansible with docs reproduced by one other member

**Comment by benhylau** [comment]
@rangermauve hey we've discussed several times before about "CI publishing a folder of static web assets onto Hypercore", I wonder if there are new developments and maybe you can give us some pointers to best practices? This is happening _now_!

**Comment by RangerMauve** [comment]
I don't have a blog post up yet, but you can use the [hyperdrive-publisher](https://github.com/rangermauve/hyperdrive-publisher) CLI to publish changes in a CI

Here's a github action that I use: https://github.com/AgregoreWeb/website/blob/main/.github/workflows/publish.yml

Essentially: 
- I used `hyperdrive-publisher create` to generate a drive.
- Saved the seed to the Secrets section on the GitHub repo
- added the generated URL to my [dat-store](https://github.com/datproject/dat-store/) instance on a Digital Ocean droplet.
- Added the github action to the repo so that on every push it'd update the site

**Comment by benhylau** [comment]
Thanks @RangerMauve.

@ASoTNetworks let's discuss
- our approach to Hypercore
- how to get static assets onto the server via API (see #23)

**Comment by RangerMauve** [comment]
I could do an hour call walking folks through it some time if you folks want.

Ideally recorded so it could be re-shared with others.

**Comment by ASoTNetworks** [comment]
@RangerMauve that would be cool and have the last part a non-recorded Q/A session.

**Comment by ASoTNetworks** [comment]
I got Ansible to provision the VM, install IPFS with systemd service, and install NGINX.

**Comment by ASoTNetworks** [comment]
I have Ansible configuring the nginx vhosts for API, one.compost.digital, and IPFS frontend.

**Comment by benhylau** [comment]
## Distributed Press services
api: api.distributed.press
http-hyper proxy: hyper.distributed.press
http-ipfs proxy: ipfs.distributed.press

## Each project
compost: one.compost.digital
  - https://one.compost.digital
  - hyper://PROJECT_HYPER_KEY
  - ipfs://PROJECT_IPFS_HASH
  - ipns://PROJECT_IPNS_KEY
  - https://hyper.distributed.press/PROJECT_HYPER_KEY
  - https://ipfs.distributed.press/ipfs/PROJECT_IPFS_HASH
  - https://ipfs.distributed.press/ipns/PROJECT_IPNS_KEY

hypha website: hypha.coop

**Comment by ASoTNetworks** [comment]
I have got the Ansibles working here https://github.com/hyphacoop/ansibles/tree/distributed-press/distributed-press/srv1.distributed.press

**Comment by benhylau** [comment]
Will review this wkend! Tks.

@bennlich this is working now https://api.distributed.press/compost/v0/monetization/balances

I know there are still minor issues with the `balance` being sometimes a string and other times an int, will fix those but this is generally how it'll look. Full API docs coming on Monday!

**Comment by benhylau** [comment]
@ASoTNetworks shouldn't we open `4001` and close `5001` for IPFS to work?

Our firewall:
```
sysadmin@srv1:~$ sudo iptables -S
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -s 10.0.1.2/32 -i eth0 -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 5001 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 42666 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 42666 -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
```

Our IPFS config:
```
compost@srv1:/home/sysadmin$ grep 'Addresses'  ~/.ipfs/config -A11
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ],
    "Announce": [],
    "NoAnnounce": [],
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080"
  },
```

**Comment by benhylau** [comment]
Rename `compost` user to `press`

**Comment by benhylau** [comment]
- [ ] @ASoTNetworks to write instructions on how to provide `~/.distributed-press/config.json`

**Comment by ASoTNetworks** [comment]
The current playbook provisions the encrypted version of `config.json` in `./distributed-press/srv1.distributed.press/roles/install-api/templates/config.json`.

To encrypt the file cd into the directory and replace `config.json` in plain text then run `ansible-vault encrypt config.json` using the deploy Ansible vault password in our Passbolt.

Make sure the file is now encrypted and you can push / PR to the repo.

**Comment by ASoTNetworks** [comment]
I have renamed the user to press in the Ansible scripts in this PR: https://github.com/hyphacoop/ansibles/pull/8
