### ISSUE TITLE
CI publish web monetized website to DWeb

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#18]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Dec 16, 2020  
🎯 **Success criteria:** Have a web monetized website published to WWW, Hypercore and IPFS through CI.  

## Task Summary

This requires #16 to determine the input website to be published, and that the baseline monetization flow works under WWW. Then it uses #17 to publish the content onto WWW, Hypercore and IPFS.

The code should be published through CI (e.g. Travis) from GitHub repository.

Verify the published website on merge-to-master, using WWW browsers, Beaker, and IPFS gateway from an independent IPFS node. Observe how web monetization works on all three systems, or document what is missing to make it work.

## To Do

- [x] Create CI script
- [x] Verify publishing to the 3 networks
- [x] Verify web monetization on the 3 networks
- [x] Document learning

**Comment by benhylau** [comment]
@ASoTNetworks I will write a guide in the README of the API, then you follow those curls to make a travis/circle CI in https://github.com/hyphacoop/compost.digital/ to publish to `staging.compost.digital` and `compost.digital`.

**Comment by benhylau** [comment]
[Guide](https://github.com/hyphacoop/api.distributed.press#guide) is done, all yours! Let's bring `staging.compost.digital` and `compost.digital` online :D

**Comment by ASoTNetworks** [comment]
Added CI scripts to deploy https://github.com/hyphacoop/compost.digital/ and opened PR there.

**Comment by benhylau** [comment]
Merged! Confirmed all links are working :)

I will add web monetization to COMPOST website and check off the last items.

**Comment by benhylau** [comment]
Added webmon to `compost.digital` and `staging.compost.digital`. Monetization to payment ptr via http is separate from DWeb protocols, and works fine when website is loaded via a local or remote gateway, or in attached natively in web browser:

![staging](https://user-images.githubusercontent.com/2261308/107791706-40e50a80-6d22-11eb-8043-5be5f31f4bfc.png)
