### ISSUE TITLE
DPress Pitch Deck 

### ISSUE THREAD

**Issue by pp2tech** [hyphacoop/distributed-press-organizing#184]
📅 **Due date:** August 2024

## Task Summary
Create basic pitch deck for partners & publishers that describes what DPress as a service does and why is it good.

## To Do
- [x] draft pitch deck structure
- [x] add DPress diagrams from Mauve
- [x] discuss draft deck with Patrick B. (guy potentially taking us to newsrooms in Russia and Iran)
- [x] get the final deck redesigned by designer 

👇  moved to its own issue
- [x] #191
