### ISSUE TITLE
DPress - Petr's final tasks 

### ISSUE THREAD

**Issue by pp2tech** [hyphacoop/distributed-press-organizing#185]
📅 **Due date:** August-2024

## Task Summary
What is left to finish before the end of our cooperation;

## To Do

- [x] Finish Pitch Deck for DPress (it is issue #184 )
- [x] re-cycle emails to those who not reacted or had out-of-office
- [x] Clean the CRM sheet - so others would understand what happened
- [x] make sure all documents and tables are in BD folder
- [x] Create market map - competition and DPress position
- [x] Create final Report with recommendations and next steps

Final Report will include:

- links to all created documents
- competition reserach
- DPress market positioning + SaaS product definition 
- Financing options for growth of the business side
- Events to consider for connecting with publishers and funders
- next steps and next activities to continue with started efforts (it was too short!)
- recommended list of Features to consider (see if some are in Git issues already)
- ....
