### ISSUE TITLE
Fundraising web page

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#19]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Dec 18, 2020  
🎯 **Success criteria:** Web page template for publishing crowdfunding goals.  

## Task Summary

Starting Dec, we expect to work with Simply Secure to decide what the UI here may look like.

In Jan, we would like to hold two sessions of collective goal-setting exercise with all the authors:

>14 JAN 2021: Discussion on collective ownership and financial success.
>21 JAN 2021: Collective strategizing on publication and monetization features.

We'll need to demo this base UI and see how goals can be drafted, and what visualizations may be included in the magazine.

Two models we want to explore with web monetization are:
1. Payments unlock **premium experiences** (e.g. crowdfund a micro-conference with the authors, an abstract/trailer developed into long-form article/full documentary in a future issue).
2. Employ **probabilistic revenue sharing** to distribute revenue among contributors on an ongoing basis (e.g. royalties).

We are currently thinking of Gitcoin and Open Collective as a "collective account" that is for building recurring revenues for the magazine. In Issue One, web monetization will also be a collective account, but later on we can make individual subaccounts for each author to enable more complex and granular goals.

See #12 for details.

## To Do

- [x] Discuss expectations and design with ~~Simply Secure~~ Mai and Udit
- [x] Implement fundraising web page with visualizations enabled by #15 
- [x] Develop sample fundraising goals and the interactions
- [x] Demo web page

**Comment by benhylau** [comment]
Pls see https://github.com/hyphacoop/distributed-press-organizing/issues/12#issuecomment-738987452

**Comment by benhylau** [comment]
API specs https://github.com/hyphacoop/api.distributed.press/blob/main/README.md

**Comment by benhylau** [comment]
![Screen Shot 2020-12-08 at 1 15 39 PM](https://user-images.githubusercontent.com/2261308/101528989-f0d27c00-395d-11eb-96a2-ebbb6edd7cf8.png)

**Comment by bennlich** [comment]
Here's a stab at a site flow + content layout for the content and fundraising pages. Some notes about how to look at these:
- The "Send Bob a tip" button at the bottom of the content page is a link to the fundraising page
- The "Give $" button is a link to the open collective page
- The "Give ETH" button is a link to the gitcoin page
- There's no web monetization stuff in here yet--that'll be next if this is the right direction
- The only "live" number is the --$CA534-- in the Issue 1 Finances section. I'm imagining this as the total value of contributions (ETH + $CA) raised by compost since launch. @benhylau  can the API provide this number? The goal bars are filled in using this same number.

A couple of guiding questions as you look at these:
- Is there any content you were expecting to see on the fundraising page that is missing?
- Is there anything you were expecting the fundraising page to communicate that is missing?

🙏🪱🪴

![Content page](https://user-images.githubusercontent.com/704368/102136459-44394400-3e0e-11eb-94d2-7a6374f397e7.png)
![Fundraising page](https://user-images.githubusercontent.com/704368/102136455-43a0ad80-3e0e-11eb-828b-3834e0f1a7b2.png)

**Comment by bennlich** [comment]
@benhylau 's message copy-pasted from chat:

@bennlich: that looks great

> The only "live" number is the --$CA534-- in the Issue 1 Finances section.

This is probably easiest to convey UX wise. It will have some limitations, like we only support USD/CAD to start, and only count the crypto tokens that I can find a conversation pair at say... coinbase. I can make this work and update the API.

> Is there any content you were expecting to see on the fundraising page that is missing?

Perhaps some thinking around different ways to "Give". e.g. OC subscription vs. one-time donation

A more relatable term for ETH that also covers ERC20 tokens and future expansions like BTC / ATOM

In the pie chart we can probably code the GFTW money in there

I know webmon UI is missing, but one bridge we can build is some animation when webmon is on, showing streaming amt, then cursor over will tell that a monthly deposit is made from the webmon to our OC.

The "Send Bob a tip!" I don't know how we can do it. We can automatically break webmon payments via PRS (prob rev share) but there isn't a modular burst of $ or crypto that goes directly to Bob, unless Bob gives an ETH addr

Lastly, I think this whole thread is better in https://github.com/hyphacoop/distributed-press-organizing/issues/19# if you are comfortable, things get lost in chat and we should default transparent

**Comment by bennlich** [comment]
> This is probably easiest to convey UX wise. It will have some limitations, like we only support USD/CAD to start, and only count the crypto tokens that I can find a conversation pair at say... coinbase. I can make this work and update the API.

:+1: 

> In the pie chart we can probably code the GFTW money in there

What is GFTW?

> The "Send Bob a tip!" I don't know how we can do it. We can automatically break webmon payments via PRS (prob rev share) but there isn't a modular burst of $ or crypto that goes directly to Bob, unless Bob gives an ETH addr

I was imagining the "Send Bob a tip!" button just sends you to the generic fundraising page, where it is explained that Bob gets a tip, and so does everyone else. We can also change the wording on the button if people think that's weird though (or, even better, if we test it and people are confused).

**Comment by benhylau** [comment]
GFTW = Grant for the Web. That's the 50k USD income we use to pay for all of this to begin with. We may have to indicate expenses somehow.

Ahh I see, I will leave it to @maisutton @uditvira to think on that button text, with the limitation being we can't facilitate a p2p transaction to a specific contributor in Issue One.

The text could also say something more collective-base like `Contribute to our fund raise`, referring to our "goals".

**Comment by uditvira** [comment]
I really like your layouts @bennlich! Great work!

I agree with benhylau that because we aren't able to do p2p transactions in the current issue, the phrase "Send Bob a tip" could be misleading. How about something short like: "Tip the contributors" which leads to the fundraising page?

**Comment by uditvira** [comment]
We currently offer three tiers of contributions on [OC (Donation, Backer, Sponsor)](https://opencollective.com/compost). Agree with ben that it'll be nice to indicate both the "one time" and "recurring" styles of $ contributions one can make.

Proposing:
- Donate money (to donation OC page)
- Donate in cryptocurrencies (gitcoin)
- Become a monthly backer (to monthly backer OC page)

Also seems like @bennlich is proposing a generic fundraising/"Understanding finances" page, where we explain what all these technologies and services are, how we're using them, and any guides around how to sign up to them in case that's required. Wondering if that should be a separate page or just a section on this page (maybe with anchor links that jump to specific parts of the page as required)?

**Comment by maisutton** [comment]
So beautiful @bennlich !! This is the first time COMPOST feels ~ real ~ 🐝

Love the pie chart, to show much is going to contributors. Really like the look of the fundraising goals -- would that be tied to our Open Collective account or would we have to update that manually?

+1 @uditvira that it could say "Tip the contributors!" or "Tip us!" or we could go even more generic with "Support us!" -- the last one might be best since we're not just asking for tips, but also regular backers.

+1 to @uditvira's proposal for the language changes above.

Re: "Understanding the finances" page -- It could all go on one page with anchor links + back to top of page links embedded through the explanations. Seems like the simpler route.

**Comment by bennlich** [comment]
> Really like the look of the fundraising goals -- would that be tied to our Open Collective account or would we have to update that manually?

@maisutton the goal bars would be tied to the compost API that @benhylau and Elon are building.

> Also seems like @bennlich is proposing a generic fundraising/"Understanding finances" page, where we explain what all these technologies and services are, how we're using them, and any guides around how to sign up to them in case that's required.

@uditvira oops! I did not mean to propose this. To clarify, my proposal is:

1) Content pages have a single button at the bottom that sends you to the fundraising page
2) The fundraising page looks like the second png above. (It may help to download it--the white on white might be adding confusion). The fundraising page links to open collective and gitcoin, lists fundraising goals, and explains where your money goes when you donate (the pie chart).
3) Probably the site header would also have a link to the fundraising page, but this is not depicted in the layouts above.

@maisutton @uditvira does this seem right to you? @uditvira are you proposing we put more info about the payment technologies somewhere on the compost site?

Thanks for all of your sweet feedback! @uditvira @maisutton @benhylau

**Comment by uditvira** [comment]
Ah, thanks for your clarification @bennlich. Each of those three points make perfect sense to me.

And yes -- I think some more information on the payment tech will be necessary. My preference is to have succinct explanations on the COMPOST site, on the fundraising page itself. We could also link out to better explanations elsewhere on the web, if we find good resources.

**Comment by benhylau** [comment]
@bennlich on the dweb publishing front, here is [the code I use to publish](https://github.com/hyphacoop/api.distributed.press/blob/main/pinning-services/index.js#L118-L128). For you to publish to IPFS locally, I think the easiest is to download IPFS Desktop then use its UI to import the generated site.

![ipfs-desktop](https://user-images.githubusercontent.com/2261308/103922844-5abb7e00-50e2-11eb-9f2b-86a1b128a6f8.png)

Of course you can also use the go client instead, and use its CLI instead. Either way, if you get CIDs that start with `Qm...` and the browser companion convert them to lowercase and won't resolve, you'd need to convert it [with this](https://docs.ipfs.io/reference/http/api/#api-v0-cid-base32) or its equivalent CLI.

**Comment by bennlich** [comment]
Cool! `ipfs cid base32 <Qm...>` worked. What's up with that? Is there like a new hash encoding that agregore doesn't support?

I uploaded the prototype here: ipfs://bafybeihywn7p3saqnsnaimwktkobtzes6gsljjtn3arnyucnnt4jf4ulee/

All the links work :)

**Comment by benhylau** [comment]
It's the `CIDv0 -> CIDv1` transition. It's been a little annoying yes 🤣 but you got it sorted. I can't seem to resolve it though, maybe you're the only one seeding it.
