### ISSUE TITLE
Set up tools and repos

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#2]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Get all the tools and repos set up and tell the team.  

## Task Summary

From discussion:

- Discuss tools (time/task tracker, semi-public chat/forum, mailing list) **due M0.1**
    - Signal -> Private Matrix chat, Signal as real-time
    - Project task tracker GitHub (for now)
    - Mailing list sign-up on website (typeform, airtable, hypha?)
- Set up repositories **due M0.1**
    - distributed.press organizing repo with project board
    - distributed.press website under hyphacoop github
    - COMPOST website under hyphacoop github

## To Do

- [x] All of the above
- [x] COMPOST folder in Drive
- [x] project@ forwarder
- [x] project github repo
- [x] invite to an open matrix chat
- [x] shared calendar
- [x] mailing list
- [x] password manager
 ~- [ ] document above on a wiki~ this item is tracked in #9

**Comment by benhylau** [comment]
## Newsletter

- [Our Networks](https://ournetworks.ca) uses [Mailman by MayFirst](https://lists.mayfirst.org/mailman/listinfo/ournetworks)
- [DOTS](https://decentpatterns.xyz/contribute/) uses [TinyLetter by Mailchimp](https://tinyletter.com/)

I want to clarify whether we want a newsletter (one way) or mail group (everyone on the list can message each other with optional approval step by admins)?

Here are some providers of Mailman that allows the latter:
- https://mayfirst.coop/en/member-benefits/
- https://www.webarchitects.co.uk/email#lists
- https://riseup.net

**Comment by benhylau** [comment]
@maisutton and @benhylau both want to use May First. Propose for Hypha to become a member, if not then Distributed Press becomes a member.

**Comment by benhylau** [comment]
Explore using Hypha as calendar provider to have a calendar that all 3 of us can edit. If this is impossible then use Google Calendar.
