### ISSUE TITLE
Dogfooding: Add Social Inbox to hypha.coop

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#200]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We should add replies to Dripline on hypha.coop by rendering them on the page. We should also hook into the Sutty CMS for the moderation queue.

## To Do

- [ ] Copy compost template replies to dripline
- [ ] set up sutty site for dripline with hypha folks as collaborators
- [ ] set up allow list via the sutty moderation interface
- [ ] Add remote follow JS snippet to template

**Comment by tripledoublev** [comment]
Are there written docs for compost template replies implementation or should I refer to the video @fauno shared with me last month?

**Comment by fauno** [comment]
> Are there written docs for compost template replies implementation or should I refer to the video @fauno shared with me last month?

I can write something but most of the things are already implemented on the compost template so you can copy them over and adapt to your needs.

There are several components:

* The in_reply_to component renders static info (currently the title and link) about the activity that's being replied to, if the post is a reply
* The interactions component renders a static thread of replies, likes and boosts
* The remote interaction component opens a modal window and asks the visitor to input their own instance to take them there, this requires JS to work, written in Stimulus

**Comment by RangerMauve** [comment]
Getting it into hypha.coop is hard due to a lack of docs. We'll aim to get it into distributed.press. We'll aim to get it working before wednesday so we can show it on a meeting with a potential client

**Comment by AnaFukelman** [comment]
Hi @tripledoublev 👋 just checking how things are going with this addition to hypha.coop, I understand that fauno and you debugged some stuff on Thursday. Let me know if you find any other blockages so I can help sort them out. We intend to have this by Wednesday, if it's possible

**Comment by tripledoublev** [comment]
hi @AnaFukelman,
currently working on removing likes and boost and only displaying replies.
i will get in touch if i require any help.
otherwise, i will report on my progress here

**Comment by tripledoublev** [comment]
I got this PR ready and tagged Mauve for review
https://github.com/hyphacoop/hypha.coop/pull/402
