### ISSUE TITLE
API endpoint for fetching signed content

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#21]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Jan 13, 2021  
🎯 **Success criteria:** Serve an API endpoint for fetching JSON plain text versions of our content with appropriate signaturing metadata.

## Task Summary

Develop API that returns JSON containers of plain text content (e.g. markdown, html) suitable for rendering in clients such as SSB and Aether. There must be a way to verify the bundle, which can be achieved by including a signature in the JSON bundle.

The exported bundles can also contain direct monetization information, which clients can choose to support / render.

## To Do

- [ ] Design schema and signaturing scheme
- [ ] Publish schema and sample content
- [ ] Design and develop API
- [ ] Sign JSON content as part of CI (requires #18)
- [ ] Serve API from an api endpoint on compost.digital domain

**Comment by benhylau** [comment]
Some relevant links for signed exchange and content registry standards:

## Signed Exchanges
- https://web.dev/signed-exchanges/
- https://web.dev/web-bundles/

## ISCN
- https://iscn.io/#linked-data
- https://wordpress.org/plugins/likecoin/
