### ISSUE TITLE
Branded magazine with final UX

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#22]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Jan 13, 2020  
🎯 **Success criteria:** Static website template with final branding and UX incorporated, hooked up to CI.  

## Task Summary

We are working with Made By Super to develop the brand and Simply Secure to develop the UX of the magazine. By start of Jan, we should have brand assets and wireframes ready to be coded into our final magazine, and have a pretty good idea of what the content would be. This task involves getting the COMPOST base ready for final content to be added.

## To Do

- [x] 2020: layout and content expectations, send the MBS (Udit)
- [x] 2020: pitch deck final (MBS)
- [x] 2021 W1: branding and styling guidelines (MBS)
- [x] 2021 W2: illustration needs, send the MBS (Udit)
- [x] 2021 W3: branded layout implemented in code (Benny)
- [x] 2021 W4: website template published to DWeb via Distributed Press (Ben)
- [x] 2021 W5: final illustrations (MBS)
