### ISSUE TITLE
API spec for Distributed Press

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#23]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Create clear API spec for Distributed Press and document their behaviour.  

## Task Summary

Distributed Press is expected to have a modular and extensible API spec to serve its various features for DWeb publishing. This may look like:

- `/v0/publication/<action>` relating to #18 
- `/v0/monetization/<action>` relating to #15 
- `/v0/identity/<action>` relating to #21 (issue two)
- `/v0/content/<action>` relating to #21 (issue two)
- `/v0/social/<action>` relating to future work in federated social layer

These can be served from `api.distributed.press/<project>` to start, but should be portable to any host. See https://github.com/hyphacoop/api.distributed.press

## To Do

- [x] Draft API spec for basic actions
- [x] Publish response schema
- [x] Publish as .md file in appropriate repo

**Comment by benhylau** [comment]
## Short-term

#18 should POST `static.tar.gz` to `/v0/publish/static/compost/?domain=one.compost.digital&apikey=API_KEY` and Distributed Press would automatically untar, cp the directory to WWW root on our server and **async** pin it on ipfs and hypercore.

## Long-term

In order to serve plain-text content (e.g. markdown assets) for #21 we'd want `assets.tar.gz` to do something like `/v0/publish/jekyll/compost/?domain=one.compost.digital&apikey=API_KEY` so we not only untar, but also build the assets before cp'ing to the WWW root.

This way, we can process our plain text assets to fulfill API requests like `/v0/content/markdown/compost/` that returns plaintext versions of our articles, with metadata such as their sig, ipfs CID, etc.

**Comment by benhylau** [comment]
Spec drafted https://github.com/hyphacoop/api.distributed.press/blob/main/README.md and will add new actions as we go.

**Comment by benhylau** [comment]
See https://web.dev/signed-exchanges/ for Identity and Content API signing
