### ISSUE TITLE
Build out Open Collective page

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#24]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Add brand assets, social media handles, and text to Open Collective page.

## To Do

- [x] Add description of project
- [x] Upload logo and imagery to customize page
- [ ] Reach out to first OC patron for feedback

**Comment by benhylau** [comment]
Cryptpad has an elaborate page for reference https://opencollective.com/cryptpad/
