### ISSUE TITLE
Distributed Press Monetization API responese on DWeb

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#25]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** 21 Dec 2020  
🎯 **Success criteria:** Get Monetizational API to respond to IPFS and Hypercore as according to API spec #23.  

## Task Summary

Periodically pin https://api.distributed.press/compost/v0/monetization/balances responses onto the IPFS and Hypercore networks. Make sure 15-min up-to-date responses are available over `ipfs://`, `ipns://`, and `hyper://`.

These periodic pinning belong to **Pinning Services** in Distributed Press repo: https://github.com/hyphacoop/api.distributed.press#architecture

## To Do

- [x] GETs over IPFS
- [x] GETs over IPNS
- [x] GETs over IPFS-HTTP proxy
- [x] GETs over Hypercore
- [x] GETs over Hypercore-HTTP proxy

**Comment by benhylau** [comment]
See https://github.com/ipfs/in-web-browsers/issues/174 for Opera Android resolution issue for IPFS DNSLink, but otherwise this works now on supported browsers:

```
ipns://api.staging.compost.digital/v0/monetization/balances.json
```

Also note https://github.com/ipfs/in-web-browsers/issues/169 when trying to access via HTTP using subdomain-based gateways. This seems like a priority that IPFS will address early next year.

**Comment by benhylau** [comment]
@rangermauve I wrote the following Promise:

```
function publishHyperdrive(seed, dir) {
  return new Promise((resolve, reject) => {
    // Publish hyperdrive to dat-store
    hyperPublisher.getURL({seed})
      .then(url => datStoreClient.add(url)) <-- PAY ATTENTION TO THIS LINE *
      .then(hyperPublisher.create({seed}))
      .then(hyperPublisher.sync({
        seed,
        fsPath: dir,
        drivePath: '/'
      }))
      .then((diff, url) => {
        console.log('diff');
        console.log(diff);
        console.log('url');
        console.log(url);
        resolve(url);
      });
  });
}
```

If I run this as is, I get this:

```
diff
{}
url
undefined
```

If I comment out line *, I get this:

```
diff
{
  url: 'hyper://4058f494eacf0d54ad11536bf5a31ab73da6ed209c55a5db8530a7534eb9d8fa'
}
url
undefined
```

In either case, my hyperdrive isn't syncing with the file system. Any idea?

**Comment by RangerMauve** [comment]
Try setting verbose:true to get some console output. Are you sure the dir is being passed in properly? It looks like there's an empty folder there or something

**Comment by benhylau** [comment]
Nothing suspicious turning on verbose:

```
Connected {
  remoteAddress: '198.50.215.6',
  remoteType: 'tcp',
  remotePublicKey: <Buffer f3 a2 c8 e5 73 4a 7c 0e 66 5b cf b6 f4 74 32 0a 6f 77 5f b9 22 80 a9 fc a0 01 f4 12 4c 4d 77 65>
}
Waiting to sync metadata
Peer has header true
Connected {
  remoteAddress: '198.50.215.6',
  remoteType: 'tcp',
  remotePublicKey: <Buffer f3 a2 c8 e5 73 4a 7c 0e 66 5b cf b6 f4 74 32 0a 6f 77 5f b9 22 80 a9 fc a0 01 f4 12 4c 4d 77 65>
}
Waiting for update 14
Initializing Hyperdrive
Finding changed files
No new changes detected { diff: [] }
Done
Seed:
[REDACTED]
URL:
hyper://4058f494eacf0d54ad11536bf5a31ab73da6ed209c55a5db8530a7534eb9d8fa
Starting sync
hyper://4058f494eacf0d54ad11536bf5a31ab73da6ed209c55a5db8530a7534eb9d8fa
Listening for peers
diff
{
  url: 'hyper://4058f494eacf0d54ad11536bf5a31ab73da6ed209c55a5db8530a7534eb9d8fa'
}
url
undefined
```

**Comment by benhylau** [comment]
Thanks for hopping onto the call to get everything sorted! Here's what we gotta do:

- [ ] @ASoTNetworks get rid of the `gateway` in https://hyper.distributed.press/gateway/4058f494eacf0d54ad11536bf5a31ab73da6ed209c55a5db8530a7534eb9d8fa/v0/monetization/balances.json on Nginx
- [ ] @ASoTNetworks open up `42666` (see [link](https://github.com/datproject/sdk))
    >`preferredPort: 42666 **Node**`: The port hyperswarm should try to bind on. You should allow it through your firewall on TCP/UDP for best results.
- [ ] @benhylau to stop using Promise like an idiot :) I was running the calls in parallel and returning garbage
- [ ] @benhylau to only do this on first run, otherwise `create` locks up
    - `hyperPublisher.getURL`
    - `datStoreClient.add`
    - `hyperPublisher.create`
- [ ] @benhylau place a mutex lock on `hyperPublisher.sync` otherwise if two processes sync on same seed the history may fork

**Comment by benhylau** [comment]
@RangerMauve it turns out `dat-store remove <url|path>` hangs the service, regardless of whether I pass a url or path, and I have to kill the process otherwise all the commands to dat-store would lock up.

**Comment by RangerMauve** [comment]
You might want to go to the storage location of dat-store on the VM and manually remove the url from URLs.json and folders.json

**Comment by benhylau** [comment]
Yup the manual removals worked. I successfully published everything once, but now I keep getting this, even after restarting the dat-store process:

```
Starting sync
hyper://1ff986e2999f9670d17121bef3fa922ac2da52b17061b8f75ea36a7ec556cf00
Listening for peers
Peer has header false
Connected {
  remoteAddress: '198.50.215.6',
  remoteType: 'tcp',
  remotePublicKey: <Buffer f3 a2 c8 e5 73 4a 7c 0e 66 5b cf b6 f4 74 32 0a 6f 77 5f b9 22 80 a9 fc a0 01 f4 12 4c 4d 77 65>
}
Waiting for update 0
Error: Unable to get Update
    at Object.sync (/home/compost/api.distributed.press/pinning-services/node_modules/hyperdrive-publisher/index.js:141:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

Something failing in the sync -> https://github.com/RangerMauve/hyperdrive-publisher/blob/default/index.js#L141

Unrelated to this, is it necessary to call `sync` at all? Wouldn't dat-store automatically observe changes?

**Comment by benhylau** [comment]
@RangerMauve can you verify the following work on Agregore?

- [ ] hyper://e207dff7087f254174b51609e4ab552dc08b9ef28d36f5885fac34d0671358b1/v0/monetization/balances.json
- [ ] hyper://api.staging.compost.digital/v0/monetization/balances.json (not supported on Beaker)

After gateway fix:

- [ ] https://hyper.distributed.press/e207dff7087f254174b51609e4ab552dc08b9ef28d36f5885fac34d0671358b1/v0/monetization/balances.json
- [ ] https://hyper.distributed.press/api.staging.compost.digital/v0/monetization/balances.json (it seems gateway doesn't support TXT records)

**Comment by RangerMauve** [comment]
@benhylau The URLs you linked to work in Agregore.

I'm not sure if dat-store had DNS support for resolving URLs, but that might be something you could find in the library.js file. I'd be down to review a PR adding it in if it's missing, but I'm kinda short on gratis time this week since I have contracts to work on. 😅

**Comment by benhylau** [comment]
On Agregore, DNS doesn't work for me but it seems to work for you, so maybe a MacOS thing?

![agregore-dns](https://user-images.githubusercontent.com/2261308/102850311-2740da00-43e7-11eb-8924-c4b099c703a3.png)

About dat-store support for TXT, it seems to not be supported in the gateway. I did this and it seems to work https://github.com/datproject/dat-store/pull/48.

**Comment by RangerMauve** [comment]
The dat-store fix looks good.

I'm honestly not sure why the DNS stuff wouldn't be working. :/ What did you set the TXT record to exactly?

Does `hyper://blog.mauve.moe` work?

Might make sense to clone [dat-dns](https://github.com/datprotocol/dat-dns/blob/master/test.js) and put your domain in there to see if the formatting is valid

**Comment by RangerMauve** [comment]
Here's the info about the DNS txt record for reference: https://github.com/datprotocol/DEPs/blob/master/proposals/0005-dns.md#dns-txt-record

**Comment by benhylau** [comment]
>Does `hyper://blog.mauve.moe` work?

Apparently yes! lol

![mauve](https://user-images.githubusercontent.com/2261308/102934763-c959d400-4472-11eb-80cb-26117643f598.png)

>What did you set the TXT record to exactly?
```
dig api.staging.compost.digital TXT +short
"datkey=e207dff7087f254174b51609e4ab552dc08b9ef28d36f5885fac34d0671358b1"
```

﻿﻿`blog.mauve.moe` is using a different method in `DEP-0005: DNS`:

```
$ dig blog.mauve.moe TXT +short
$ dig blog.mauve.moe A +short
165.227.36.113
$ curl http://blog.mauve.moe/.well-known/dat
dat://94f0cab7f60fcc2a711df11c85db5e0594d11e8a3efd04a06f46a3c34d03c418
ttl=3600
```

It appears that Agregore supports [.well-known/dat](https://github.com/datprotocol/DEPs/blob/master/proposals/0005-dns.md#well-knowndat), but not the [DNS TXT record](https://github.com/datprotocol/DEPs/blob/master/proposals/0005-dns.md#dns-txt-record).

**Comment by benhylau** [comment]
Both of these work in Agregore now since we fixed the dat-store:
- hyper://staging.compost.digital
- hyper://api.staging.compost.digital/v0/monetization/balances.json

**Comment by benhylau** [comment]
Response updated to include total estimated balance.
