### ISSUE TITLE
FOSDEM 2021 presentation

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#26]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Jan 13, 2021 (for recording)  
🎯 **Success criteria:** Record presentation for FOSDEM and present.  

## Task Summary

We will be presenting COMPOST + Distributed Press at FOSDEM:

- Title: COMPOST: Exploring artist-centric development through Distributed Press
- Subtitle: Towards a decentralized and interdependent publishing ecology
- Devroom: Beyond Blockchain - Distributed Web
- Time: 10 mins + QA
- Format: Lightning Talk

Working links:

- Application: https://docs.google.com/document/d/1nfR9zsZBL7PJoleR9wlwKyVppG19xasbEvU8vOCxZLc/edit
- Deck: https://docs.google.com/presentation/d/1Fb1zgHBOMC2dcArpnIii7SzLVMIHvFNDQsXQZYhhBCI/edit#slide=id.gabb78940f1_1_12
- Guidelines:
  - https://github.com/blackbeard334/fosdem21-emulator-devroom-cfp/blob/main/SPEAKERS_GUIDE.MD
  - https://github.com/FOSDEM/video/wiki/FOSDEM-2021-video-email-to-speakers

## To Do

- [x] Join coordination call on Tuesday, January 12th at 6 pm Universal time (call details in acceptance email)
- [ ] Register each of the speakers in the FOSDEM system, add profile pic and bio: https://penta.fosdem.org/user/new_account/FOSDEM21
- [x] Create [deck](https://docs.google.com/presentation/d/1Fb1zgHBOMC2dcArpnIii7SzLVMIHvFNDQsXQZYhhBCI/edit#slide=id.gabb78940f1_1_12)
- [x] Record 10 min video before Jan 13
- [ ] Join live Q&A

**Comment by uditvira** [comment]
I updated the agenda/outline for this presentation [here]( https://docs.google.com/document/d/1nfR9zsZBL7PJoleR9wlwKyVppG19xasbEvU8vOCxZLc/edit) with some rough guardrails around timing for each section.

**Comment by benhylau** [comment]
>Register each of the speakers in the FOSDEM system, add profile pic and bio: https://penta.fosdem.org/user/new_account/FOSDEM21

Do we each need to do this individually?
