### ISSUE TITLE
Implement publish action in Publication API

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#28]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Jan 22, 2021  
🎯 **Success criteria:** Support authenticated POST API to publish site to Distributed Press server.  

## Task Summary

Develop [`publication/publish`](https://github.com/hyphacoop/api.distributed.press#publication-api) POST API.

See also #23 and #18.

## To Do

- [x] Update project config
- [x] Implement POST and API to receive site assets
- [x] Coordinate with #17 to pick up assets for WWW and DWeb hosting of assets
- [x] Update README

**Comment by benhylau** [comment]
For this last item, we have the following TODOs for the ansibles:

- [ ] @ASoTNetworks upload new encrypted config to ansible (without `activeProjects[]`
- [ ] @ASoTNetworks make changes in `press-publish` and NGINX templates, for both www and api
- [ ] @ASoTNetworks disable staging flags everywhere
- [ ] @benhylau to fix API code
- [ ] @ASoTNetworks to pull new API code and make sure all services restart properly
- [ ] @benhylau to file new issue to purge old uploads in API

**Comment by benhylau** [comment]
@ASoTNetworks for the config.json we also have the option of copying it over from here https://github.com/hyphacoop/api.distributed.press/blob/main/backend/config.template.json then have ansible replace the fields with its vars. Either way works.

**Comment by benhylau** [comment]
@ASoTNetworks approved https://github.com/hyphacoop/ansibles/pull/11/files and rdy to redeploy!
