### ISSUE TITLE
Purging old data that accumulate on the server over time

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#30]
🎟️ **Re-ticketed from:** #28  
📅 **Due date:** N/A  
🎯 **Success criteria:** Implement a purge strategy for various types of data that accumulate on the server over time.  

## Task Summary

Right now the `uploads` folder retains all uploaded files that failed to be processed. This is useful for retaining debug data, but we should purge them after a week to avoid building up massive amounts of garbage.

Another place we are building up old data is our IPFS/Hypercore pins of our projects' `api` data, which changes every 15 minutes and they are all in IPFS/Hypercore storage.

## To Do

- [x] How is `df` doing on our server (post here?)
- [ ] Decide some purge policy
- [ ] Implement purge scripts

**Comment by ASoTNetworks** [comment]
Currently we are using 9% of 35G
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        40G  3.2G   35G   9% /
```

**Comment by YurkoWasHere** [comment]
## ipfs NO-COPY flag 
Flag means don't copy the file to the IPFS repo and instead reference it off the filesystem.

I don't think this is a good way to deal with it as the source file keeps changing. I dont know what long term effects this would have on having so many hashes that point to a file that is not the correct content.

## IPFS Pinning - default behavior
A interesting possibility is to stop pinning content. The pinning services re-adds the content to IPFS every cycle anyway, and pinning just prevents the GC (garbage collector)  from removing it. So if GC is run and the content is removed, the next cycle it will just be re-added.

This way running the GC would cleanup all the old content. This is unless you want to hold on to the "old" content for a long time. (GC will purge ALL non pinned content when activated.)

Some reference: https://www.ctrl.blog/entry/ipfs-repo-cache-gc.html
> The garbage collector isn’t even enabled by default and caches can grow unrestrained unless garbage collection is run manually or enabled to run on a schedule.

>The repository garbage collector does run every hour (configured by the GCPeriod option) when enabled (--enable-gc). It doesn’t delete anything from the cache unless the cache exceeds 90 %  (configured by the StorageGCWatermark option) of the 10 GB default maximum cache storage space (configured by the StorageMax option.)

> The entire cache is deleted in one go when the garbage collector runs; it doesn’t only delete enough data to bring the total size down to 90 % of the available size. Pinned resources is never deleted by the garbage collector.

**Comment by benhylau** [comment]
>ipfs NO-COPY flag

Yup, we cannot do no-copy here bc we are using ipfs to archive historic versions. I wonder if we want to stop pinning really old versions (say > week old) to keep a somewhat constant rate of disk use.

What would it take to purge things more than X days old? For:
- IPFS (should be pretty easy, using a file to track [ timestamp -> hash ] and unpin > X days)
- Hypercore (no idea, need research)
- `uploads` folder

@ASoTNetworks can you suggest something?

**Comment by ASoTNetworks** [comment]
For IPFS we can use a file to track like you suggested that is created by the pinning process and for `upload` I can have a script looks in the `upload` directory and delete after X days based on age.

**Comment by benhylau** [comment]
I think the approach makes sense, except the pinning service should be responsible for all of it, and the "purge policy" (e.g. purge at all, or x days) should be a param in main config.

**Comment by YurkoWasHere** [comment]
If you keep track of the pinned hashes by date in a log some where, you can unpin them after X days and run GC to get rid of them
