### ISSUE TITLE
Call series about Distributed Press and related topics

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#39]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Hold a series of public calls with people interested in Distributed Press and related topics.  

## Task Summary

Over April, I have chatted with many people who either expressed interest in using Distributed Press or are working on related projects. I hope to organize 4 calls over May to have some discussion time with whoever is interested in these topics.

The calls are pretty casual and not meant to build upon one another, so people can feel free to drop into any one of them as the topic interests them.

Please comment on the issue with Session number if you are interested, and optionally write about why you are interested in the topic. The times are proposals, so feel free to propose if it doesn't work for you, but the hour of the day is chosen so people in different time zones have a chance of attending.

| Session | Proposed Date | Description | Moderator |
|:--------|:--------------|:--------|:----------|
| 1 | May 5 | Distributed Press intro + [server walkthrough](https://github.com/hyphacoop/api.distributed.press/issues/10) + [hyperdrive-publisher testing](https://github.com/hyphacoop/distributed-press-organizing/issues/33) | @benhylau |
| 2 | May 12 | [Sutty.nl](https://sutty.nl) platform walkthrough | @fauno |
| 3 | May 19 | Discussions about [Social API](https://github.com/hyphacoop/api.distributed.press/issues/13) with Matters.news (Webmention, Microformats2, unwalled.garden) | @benhylau |
| 4 | May 26 | Discussions about [Content API](https://github.com/hyphacoop/api.distributed.press/issues/14) (Markdown & RSS syndication, [ISCN](https://github.com/likecoin/iscn-specs)) | @benhylau |

Here is my proposed time each Wednesday:

| Location | Local Time | Time Zone | UTC Offset |
|:---------|:-----------|:----------|:-----------|
| San Francisco | Wednesday, 5 May 2021, 08:00:00 | PDT | UTC-7 |
| Toronto | Wednesday, 5 May 2021, 11:00:00 | EDT | UTC-4 |
| Buenos Aires | Wednesday, 5 May 2021, 12:00:00 | ART | UTC-3 |
| Valencia | Wednesday, 5 May 2021, 17:00:00 | CEST | UTC+2 |
| New Delhi | Wednesday, 5 May 2021, 20:30:00 | IST | UTC+5:30 |
| Beijing | Wednesday, 5 May 2021, 23:00:00 | CST | UTC+8 |

[See other time slots in these cities](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20210505&p1=325&p2=250&p3=224&p4=176&p5=33&p6=51).

## To Do

- [x] Session 1 ([recording](https://ca.meet.coop/playback/presentation/2.0/playback.html?meetingId=ec7db1d978f1eb1c129131f78f08bf2892601f0c-1620226700575) 1.5h)
- [x] Session 2 ([recording](https://ca.meet.coop/playback/presentation/2.0/playback.html?meetingId=ec7db1d978f1eb1c129131f78f08bf2892601f0c-1620831337412) 2.75h)
- [x] Session 3 ([recording](https://ca.meet.coop/playback/presentation/2.0/playback.html?meetingId=ec7db1d978f1eb1c129131f78f08bf2892601f0c-1621436312744) 1.5h)
- [x] Session 4 ([recording](https://ca.meet.coop/playback/presentation/2.0/playback.html?meetingId=ec7db1d978f1eb1c129131f78f08bf2892601f0c-1622041732444) (1.5h)

**Comment by benhylau** [comment]
@fauno does the Session 2 time work for you guys at Sutty?

**Comment by benhylau** [comment]
@guoliu Session 3 is what we discussed, but maybe Session 4 as well!

**Comment by benhylau** [comment]
@YurkoWasHere @ASoTNetworks I hope you guys can attend Session 4, as they relate to work needed by COMPOST Issue Two!

cc. @uditvira @maisutton

**Comment by benhylau** [comment]
@martinheidegger @dpaez @YurkoWasHere would you guys be able to attend Session 1? I want to walk through the code running on dev server and show the hyperdrive-publisher bug.

**Comment by benhylau** [comment]
@cinnamon-bun @luandro @arunk @salus-sage @tbdinesh feel free to attend any of these!

**Comment by martinheidegger** [comment]
I am in!

**Comment by fauno** [comment]
> @fauno does the Session 2 time work for you guys at Sutty?

Sounds good!  [According to this it'll be at our 12:00](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20210505&p1=325&p2=250&p3=224&p4=176&p5=33&p6=51), every Wednesday?

**Comment by benhylau** [comment]
@pfrazee also confirmed for Session 3 since that's relevant to unwalled.garden and [ctzn](https://github.com/pfrazee/ctzn).
@martinheidegger great! glad you can make it!
@fauno sorry I didn't realize the timezone in BA is one hour off from Toronto. Added to top post.

**Comment by guoliu** [comment]
> @guoliu Session 3 is what we discussed, but maybe Session 4 as well!

The time works perfect for me. Thank you for organizing @benhylau ! Yes I'm interested in both Session 3 and Session 4, excited to learn what everyone thinks!

**Comment by benhylau** [comment]
We start Session 1 tomorrow!

### _CALL LINK: https://link.hypha.coop/compost-calls_

(Call link added to top post as well.)

**Comment by martinheidegger** [comment]
@benhylau Correct? https://www.timeanddate.com/countdown/generic?iso=20210505T08&p0=224&font=cursive

**Comment by benhylau** [comment]
Yup that's right!

**Comment by benhylau** [comment]
@martinheidegger we're starting now ;)

**Comment by fauno** [comment]
Hi! Thanks for the walkthrough, here are some comments and questions.
Maybe they've been answered elsewhere so feel free to point me to the
docs :)

* What kind of resources does the pinning service need?  Do you have
  some kind of projection for its growth?  In our very limited tests,
  sometimes IPFS peaks CPU usage while doing nothing so we got a little
  worried about that.  We haven't tested Hypercore yet.

* If we wanted to run a node for Distributed Press, would be need to run
  distributed-pinning.service or only IPFS and/or Hypercore nodes?  We
  have plans to host file uploads on IPFS.  We're currently using
  Syncthing to distribute websites throughout our two-node
  infrastructure with good results and little resource usage and
  monitoring.

* About monetization, what kind of services are you planning to support?
  From the [backend
  code](https://github.com/hyphacoop/api.distributed.press/blob/main/backend/index.js#L80)
  I get that you fetch regularly from other services, so it could be
  anything, right?  Do you plan on gatewaying payments or how are
  monetization methods going to be generally available?

  Maybe I should read more about Web Monetization first, are there some
  resources you can recommend?

  We're adding support for pay-what-you-can/crowdfunding/donations on
  our store platform right now and one of the plans is to be able to
  fetch balances through its API, so they look very similar :)

* Is there an API client for the browser?


See you next week!  Nice to meet @martinheidegger :)

**Comment by benhylau** [comment]
Some links shared during the Session 1 call: 
- https://github.com/dat-ecosystem/organization
- https://sutty.nl/en/
- https://0xacab.org/sutty/distributed-press-api-client
- https://github.com/RangerMauve/hyperdrive-publisher/issues/11

**Comment by benhylau** [comment]
@fauno answers to your questions

>* What kind of resources does the pinning service need?  Do you have
  some kind of projection for its growth?  In our very limited tests,
  sometimes IPFS peaks CPU usage while doing nothing so we got a little
  worried about that.  We haven't tested Hypercore yet.

We have only a couple websites on there, so no idea what resource consumption is at scale. @ASoTNetworks can you give some input on our VM spec at the moment?

Our API responses are currently pinned and never erased, so that does build up over time as each one has a different timestamp.

>* If we wanted to run a node for Distributed Press, would be need to run
  distributed-pinning.service or only IPFS and/or Hypercore nodes?  We
  have plans to host file uploads on IPFS.  We're currently using
  Syncthing to distribute websites throughout our two-node
  infrastructure with good results and little resource usage and
  monitoring.

You'd need to run IPFS, dat-store, and run all three services associated with Distributed Press (API, backend, pinning). Distributed Press is very light-weight, it's essentially glorified cron jobs.

>* About monetization, what kind of services are you planning to support?
  From the [backend
  code](https://github.com/hyphacoop/api.distributed.press/blob/main/backend/index.js#L80)
  I get that you fetch regularly from other services, so it could be
  anything, right?  Do you plan on gatewaying payments or how are
  monetization methods going to be generally available?

Monetization currently does not touch Web Monetization. It only calls REST APIs of Open Collective and Etherscan, to get balances of OC and ETH addresses, and convert into the base fiat currency equivalent. Everything is read only. We have thought about reading Web Monetization balances, but it is not currently possible unless we code to specific and authenticated Uphold APIs, which we don't want to do.

>  Maybe I should read more about Web Monetization first, are there some
  resources you can recommend?

These are done at the COMPOST magazine level, and is out of scope for Distributed Press for now. This can be a good general resource: https://webmonetization.org/docs/getting-started

More about our use [here](https://community.webmonetization.org/udit/compost-grant-report-1-1g1l) in a publishing context.

>  We're adding support for pay-what-you-can/crowdfunding/donations on
  our store platform right now and one of the plans is to be able to
  fetch balances through its API, so they look very similar :)

This would probably be similar to how we fetch from OC's API.

>* Is there an API client for the browser?

No but you look at "bake sale" code from [this page](https://one.compost.digital/support-us/). Also the footer is how we link to gatewayed pages on IPFS and Hypercore.

**Comment by benhylau** [comment]
## Session 2

- [**Recording** (2.75h)](https://ca.meet.coop/playback/presentation/2.0/playback.html?meetingId=ec7db1d978f1eb1c129131f78f08bf2892601f0c-1620831337412)
- Description: Walkthrough of the Sutty.nl platform for creating Jekyll-based static websites. Themes and content are managed by Sutty's free software platform, so we can ensure 100% compatibility for DWeb publishing. Deep dive into Sutty's UI, design decisions, schema, and 30+ Jekyll plugins they developed over the years to support their various client needs. Super cool stuff!

## Some links shared during the Session 2 call: 
- https://sutty.nl/en/
- https://0xacab.org/sutty/
- https://twitter.com/SuttyWeb/status/1392618903973543936
- @benhylau: we're almost at 3 hours yo~
  - @fauno: [si ya saben como soy para que me invitan](https://www.youtube.com/watch?v=gU5kIrtmyn4)

_(Updated with recording on May 13)_

**Comment by benhylau** [comment]
## Session 3

- Recording (1.5h) _TBA_
- Description: The discussion started with distributed vs. federated content networks, and incentives to sustain necessary centralization points such as gateways and aggregators. Then we discussed how to structure social graphs, content feeds, content storage and exchange formats, existing standards for social messages like Webmentions, and how commons principles relate to various components that need strict consensus and hence active governance.

## Topics (with points of clarification):
- Paul: Distributed Vs. Federated
  - e.g. federated ~ mastodon
  - e.g. IPFS gateway. content is accessible on the "mesh"
  - technologically and UX is novel
  - how to deal with cost structure?
- Guo: content feed+social graph as a distributed publication and social network
  - trying to design a minimal social graph
  - ppl can store social graph in their protocol
  - get into problem Paul is talking about, we need an aggregator! so we can search, notify, etc.
  - readers access aggregator
  - Flancian: generating commons?
    - Ben: mastodon?
- Flancian: minimum viable exchange format / interchange protocol
    - Entity markup as a possible pareto-sweet-spot :)
    - from personal knowledge management space
    - from that, to "data mesh"
    - lots of these tools end up going in different directions
    - export to markdown with one extension
      - [[ entities ]] that can be looked up (arbitrary unicode text)
- Ben: Webmentions + Microformats on DWeb
- Vera: What do you think about "wikilinks" as a name / concept
- Ben: Unwalled Garden
- Ben: Distributed Press

## Some links shared during the Session 3 call:
- https://matters.news
- https://ctzn.network
- https://anagora.org/underlay
- https://anagora.org/ctzn-network
- on moderation of comments, and more generally "content"
  - https://jaygraber.medium.com/designing-decentralized-moderation-a76430a8eab
  - https://aether.app/blog/

**Comment by benhylau** [comment]
## Session 4

- **Recording** (1.5h) TBA
- Description: Discussed DWeb ecosystem and publishing in Asia. Origin stories of LikeCoin, Matters, Distributed Press/COMPOST. Touched on project statuses in relation to Cosmos, Web Monetization, IPFS publishing. Project goals and timelines for ISCN and Distributed Press, explored integration plans, what the APIs will look like.

_We have proper notetaking this time wow._

Topic: Content publishing formats

### Who's here

    Guo (Matters)
    Edmond Yu (LikeCoin)
    William (LikeCoin)
    Benedict (Distributed Press/COMPOST)
    Phoebe (LikeCoin)
    Udit (Distributed Press/COMPOST)
    Jieping (Matters) - briefly

### Intros
- Benedict: Working on distributed press, with Mai/Udit, COMPOST, working on the distributed web space for a couple years, work at hypha (co-op), aether (Decentralized reddit)
- Edmond: COO of Likecoin, looking at likecoin, very related to Distributed Press. Ben's in the discord channel sharing links, which were resonating with LikeCoin community. Wants to build tech that is owned by and is helpful to civilian community
- Phoebe: working with Edmond + William. Comms/Journalistic background in the US. Bg in blockchain. Met likecoin, inspired by potential to empower media/journalists. First launched monetization at Matters a year ago. Now focus on ISCN registry on LikeCoin chain, with metadata, also stored the actual content on IPFS. Now also working on Gov. Individuals can vote on proposals on chain (bond POS). Users in HK/Taiwan.
- William: Tech side. Motivation: monetization progress, "ISCN" is the spec for attribution, metadata storage. Started with Ethereum but now migrated to Cosmos. Likecoin chain uses Cosmos SDK.
on-chain metadata to content on IPFS. 
link to reference with schem: ISCN.io
- Guo: Engineer at matters. Matters is a decentralized social network. Lots of centralized servers currently. Looking to decentralize: discovery etc. Interested in socially connected RSS. ISCN is the entry point is the "content", entry point on matters is a "person". This is why matters and ISCN are complementary.
- Udit: engineer, product strategy, Ben with Distributed Press, more on COMPOST, work with creators, on-ramp for these technical topics. hypha.coop infrastructure projects, also services, involved in Cosmos Hub governance practices. Interviewing stakeholders, social processes around their proposal flow.

### Agenda
- Matters origin story, collab with LikeCoin
    - also what kind of creators are currently in this space? what are their motivations to use this decentralized social media?
- Eastern vs. Western perspective to decentralized publishing
- LikeCoin
    - relationship to cosmos hub?
    - relationship with traditional publishing 
- Web Monetization
  - Is it possible to integrate LikeCoin with WM?
- Distributed Press Q&A
- ISCN
  - How did the standard come about?
  - How does the integration of IPFS looks like?
- NFT ambitions?
- CTZN, Sutty
- Creator onboarding
- How Distributed Press (or other projects Ben is working on) would like to integrate with ISCN, what is your current data structure or product plan?

### Notes
- Matters and LikeCoin collab on grant apps including Google News Grant. 
- Frictions are practical and not do with ideology etc.
- Matters motivation: surface good content rather than driven by attention economy. Jjieping has background in content publishing (editor in a well known independent channel). LikeCoin collab is very natural from a monetization standpoing, i.e., how do we map reputation and readership to value that's provided creators.
- Motivation for creators: free platforms aren't that common in HK/TW. Also censorship resistant. Jjieping is well connect to creator ecosystem. Feeling of community is very important. How can slice the community in to pockets
- Ben: hope for independent media. Distributed tech interested started from community networks/mesh networking. Met Mai in Oakland hacklab also DWeb. Mai has a background in writing/editing. 
- Udit: corporate consolidation harder to talk about than censorship, Western harder onboard, "harder sell"
  - Medium, Facebook has very accessible UX
- Phoebe: social context hard to explain, what's happening in political world hard to relate to the tech
  - Hard to propose even to Cosmos community, publishing vs. DeFi, not enough attention from even blockchain community
  - Easier to connect with users than blockchain community
  - 90% users don't know about blockchain
- Guo: huge gap with investors
  - focus in east is anticensorship
  - focus in west is anticapitalism
      - interested in "decentralization" as a concept/ideology, very intrisinc to american culture and history, whereas in the east is not so obvious. east is focused on result vs. actual tactics. in china atleast people are very interested in DeFi rather than decentralization
- why is hard to get attention for eastern projects within western spaces?
    - is it because of cultural distance?
    - or because publishing is disconnected from DeFi?
    - Phoebe: monetization is an important piece here because it fullfills a material need rather than the publishing side which fulfills a more social/cultural need so it requires more linkage. Needs communication and story telling 
    - GTM strategy: forbole's angle is to be a validator to get attention within international community. Adobe who has a lot of capital, they still have trouble with communication around content registration
- Guo: DeFi tech is easier, publishing is a little harder. Also the disruption is much harder. In a sense, web was already decentralized but not actually 
- Udit: import reputation in... COMPOST try to do this
    - what are the new affordances, new _kinds_ of content that can be created, that cannot be on centralized web
    - collaborative content, etc.
- Guo: what is the killer feature of the Dweb? because twitter etc. have networks.
    - anti censorship is the killer feature. can move content across information borders/splinternet.
    - unique ID that can be shared across network boundaries, which can deal with the fragmentation among dweb protocols/projects
- Phoebe: Web Monetization, participating in community but not quite main focus.
- William: very much compatible with original Cosmos hub, planning to enable IBC in the future. Thinking about interchain applications in the future.
- Web Monetization: concept of ID per user, but are looking into decentralizing this idea (maybe using blockchain). 
- IBC integration can link to web monetization by facilitating exchange between other tokens
- Question: what kind of data do you want to put on ISCN?
Benedict:
    - LikeCoin can use signal of "like" to initiate monetization?
    - Build Web Mon into your plugin as a straightforward use case
William:
    - Users have barrier because they already have wallets, can't expect them to be setting up a new wallet for web monetization and KYC
    Benedict: 
    - Wallets are becoming new points of centralization
Phoebe:
    - Payment pointer is too complex for lay users. UI is not user friendly
    - Current focus is likecoin ecosystem
    - Before keplr existed we had our own wallet
    - or keep as crypto
        - stick within ecosystem and use it for staking
Benedict: for Distributed Press, uniform urls is important
    - static sites are pinned on IPFS and made available over hypercore
    - also serves an API aside from static content
    - interested in what community standards are emerging and how we can integrate those into our project. ISCN is a standard we're interested in for content registry. Similarly looking for standards for social/identity
    - We want to support multiple standards where no clear winner for the standard (e.g., identity)
- William: OAuth API via LikeCoin app, internally submit to chain, or chain API in early days
    - end of next month, mainnet upgrade, soon after have early demos
- Ben: timeline-wise, prob go to your demo and plan Issue 3 to be published with ISCN
- Phoebe: interested in being our validator?
    - Ben: I will ask Udit (before or after upgrade)
    - Phoebe: if you join after upgrade it's one time
    validator setup docs: https://docs.like.co/developer/become-a-validator

### Links
- http://docs.like.co/
- http://like.co/
- https://iscn.io
- https://wordpress.org/plugins/likecoin/
- https://json-ld.org
- https://www.forbole.com/blog/forbole-has-voted-no-to-proposal-47-on-cosmos-hub/
- https://github.com/hyphacoop/api.distributed.press
