### ISSUE TITLE
Social media strategy

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#4]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Start social media accounts and announce project.  

## Task Summary

Start social media accounts and announce project.

## To Do

- [x] COMPOST Twitter -> make brand account with @maisutton and @benhylau
- [x] Are.na: Publications, cooperatives/solidarity, quotes, articles -> @maisutton @uditvira 
- [x] COMPOST Instagram @maisutton 
- [x] SSB -> personal @benhylau
- [x] Mastodon -> mastodon.coop, the main one

**Comment by benhylau** [comment]
@maisutton to set up on Twitter

**Comment by uditvira** [comment]
@maisutton registered `compostmag` on Twitter

**Comment by benhylau** [comment]
Mai to:
- Squat Insta
- Post on SSB
- COMPOST OC account apply to social.coop and use Mastodon
- Invite @uditvira from opencollective.com/hyphacoopinc

**Comment by maisutton** [comment]
I'm closing this issue because all the To Dos are done on it. Woohooo
