### ISSUE TITLE
Distributed Press production hardening: Add Prometheus-based monitoring to the Distributed Press production environment and polish APIs for  multi-tenant use.

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#41]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

This will involve updating our dependencies for p2p, restructuring how data gets pinned via pinning services in addition.

## To Do

- [x] Update protocols
- [x] Integrate pinning services
- [x] Multi-tenant API
- [x] Promethius monitoring for stats

**Comment by RangerMauve** [comment]
One thing we should discuss is the sorts of things we want to track regarding metrics.

The HTTP API is an obvious one, but there's probably metrics we can gain from the p2p protocols.

E.g.
- Incoming peers + their IPs/IDs
- Incoming / outgoing traffic
- Connectivity errors?

**Comment by RangerMauve** [comment]
We've got this in the latest PR. Only thing missing is DNS. Will close this once that's in
