### ISSUE TITLE
Sutty integration: Integrate Distributed Press into Sutty platform by automatically fetching a Distributed Press API token for every website, and adding a “publish to DWeb” toggle to their interface.

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#42]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

...

## To Do

- [ ] ...

**Comment by sutty-coop** [comment]
Here's the overall milestone split in issues across different projects: https://0xacab.org/groups/sutty/-/milestones/1

Specifically for this issue:

- [ ] [Implement site creation API on client](https://0xacab.org/sutty/distributed-press-api-client/-/issues/2)
- [ ] [Onboard Sutty's users into Distributed Press integration](https://0xacab.org/sutty/sutty/-/issues/7840)
- [ ] [Implement API client on the CMS](https://0xacab.org/sutty/sutty/-/issues/7839)

**Comment by fauno** [comment]
Updates:

* The UXWG is working on the CMS UX for the integration
* We have initial integration with APIv0 (current version) with manual configuration (no UX, just from the CMS console) intended just for legacy sites (distributed.press, sutty.ml)

**Comment by sutty-coop** [comment]
Details about UXWG:

Analized different user design processes and decided what to adress long term and short term 

Short term - design thinking alike methodology for an improvement of the functional development and usability of 
the panel, to incorporate the DWeb toggle adequately

Long term - workshops with the selected community/local-first networks, collectives, journalists, etc for their onboarding 
    
Panel re-design:

Mapping internally to Sutty the usability problems found in the user flow of Sutty panel, from the starting point in our landing to the final activity of posting and editing content.

Inviting a Compost representative (Mai) to map usability problems in the user flow of Sutty panel.

Gathered and prioritizing the problems, currently narrowing issues

Currently creating a survey to rank which problems to prioritize and mapping the information architecture

**Comment by fauno** [comment]
Updates:

- [distributed-press-api-client](https://0xacab.org/sutty/distributed-press-api-client) v0.2.0 has been released as a [gem](https://rubygems.org/gems/distributed-press-api-client)
- Panel integrates the API client, uses a publisher token, refreshes it periodically and creates sites on activation
- Panel supports any number of DP instances but there's no UI for this so it only uses the first one available
- New UX is designed, but not implemented yet, there's a toggle available on site config meanwhile
- Onboarding texts are being written by Ania and Mai

So everything should be ready for testing then DP is deployed :mechanical_arm: 

We'll need a token with publisher and refresh capabilities.

**Comment by fauno** [comment]
Updates:

* The toggle is already working on the CMS
* When changes are published you get an email with all the dweb links
* Only thing left to test is site removal, DP threw a 500 error when we disable the toggle

**Comment by RangerMauve** [comment]
This is done and working I think? @fauno Feel free to re-open if we've still got TODOs
