### ISSUE TITLE
DNS management delegation: Distributed Press to manage the websites’ DNS records, may push DNS record changes to Sutty via a new Sutty API (instead of the default DigitalOcean API) as part of the DWeb publishing flow.

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#43]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We will be adding a custom DNS server implementation which will resolve [DNSLink](https://www.dnslink.io/) requests for sites.

## To Do

- [ ] Add DNS server config
- [ ] Add handler for resolving _dislink subdomains, error on any other format. Only support TXT records
- [ ] Fetch the site data for a given domain from storage
- [ ] For each p2p link, generate a dnslink entry
- [ ] Add a new HTTP route which returns the DNS server and gateway roots for DP `{dns: 'x.y.z', gateway: 'https://api.distributed.press'}`
- [ ] Deploy to cloud (ask Elon and Yurk for help)
- [ ] Test setting a DNS record to delegate a domain to our DNS server, and resolving it with dnslink
- [ ] Sutty should fetch the DNS server from the config endpoint when adding a new DP backend
- [ ] Test resolving DNS in Agregore
- [ ] End to end flow of creating a site, delegating DNS, uploading data, loading it in Agregore

**Comment by sutty-coop** [comment]
- [ ] [Support DNSLinks on Sutty's DNS](https://0xacab.org/sutty/ansible-sutty/-/issues/2)

**Comment by fauno** [comment]
@RangerMauve are there other zones other than `_dnslink` that need to be delegated?

**Comment by fauno** [comment]
We would deploy something like this: https://0xacab.org/sutty/ansible-sutty/-/merge_requests/6/diffs

**Comment by RangerMauve** [comment]
> are there other zones other than _dnslink that need to be delegated?

Should just be DNSLink

**Comment by RangerMauve** [comment]
This is now done if I understand correctly.
