### ISSUE TITLE
Update hyperdrive-publisher to latest version

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#49]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We need to update the hypercore-protocol bits of distributed press to the latest stable version. This will give us performance improvements and hopefully some improved stability.

Part of this will also involve deprecating dat-store and hyperdrive-publisher since they don't give us any advantages at this point. Instead we'll embed a hypercore node right into the stack alongside IPFS.

We can look into pinning services after the first milestone is done and working.

...

## To Do

- [x] Update hyper-sdk [@v4.0.0](https://github.com/RangerMauve/hyper-sdk/pull/99)
- [ ] Make small example of pushing to hyperdrive from a folder
- [ ] Update distributed press hyper publishing code

**Comment by RangerMauve** [comment]
Changing this a bit to reflect changes in how the architecture will work.

- Still using hyper-sdk
- Going to skip dat-store and hyperdrive-publisher (for now)
- Going to use `mirror-drive` to sync to and from hyperdrives.
- We'll wrap this in a protocol backend in DPv1

**Comment by RangerMauve** [comment]
Instead of using hyperdrive-publisher we're using hyper-sdk, this is in the latest protocols PR
