### ISSUE TITLE
Summer workshops

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#5]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Host workshops at DAT CEE and Our Networks.  

## Task Summary

Plan and facilitate summer events!

- Dat CEE (accepted, see email) @maisutton
- [Our Networks 2020](https://github.com/ournetworks/2020-submissions/issues/34) @benhylau 

## To Do

- [x] Discuss what the conference workshop format is
- [x] Host workshop at DAT CEE (July 30-31)
  - _@benhylau is on vacation this week_
- [x] Host workshop at Our Networks 2020 (~~August 7-9~~ September 8-13)
  - @maisutton to respond to confirm
- [x] Record output
- [ ] Plan continued engagement with people interested

**Comment by benhylau** [comment]
Accepted Dat workshop with @maisutton @uditvira as presenters.

>This collaborative workshop prompts discussion around precarious and hidden labour in digital authorship and open source development. Through conversations and drawings, we will explore tensions between social purpose vs. free labour, and our atomization in a competitive content market as creators.
>
>Inspired by Holistic Security by Tactical Tech and the Revolutionary Networked Politics presentations at transmediale, we will engage through a holistic approach that centres on self-care and the well-being of content authors. There are many topics relevant to digital publishing, such as: equitable compensations and dignified livelihoods, creative expression on moderated platforms, security and anonymity in online spaces. How does one navigate the complex environments and entrenched power structures of the Web? What is the cost of the labour asked of an individual creator and the impact on their well-being?
>
>As an initiative of the Distributed Press project, and inspired by a surrealist parlour game, we will assemble the words and images generated during our workshop to compose a work of collective authorship to express our aspirations for the future web.

**Comment by benhylau** [comment]
https://docs.google.com/document/d/14LYiHr0B7VzJpl3KeKm3GLvWiRr6vSJtgUIAtJaVXFs/edit#

**Comment by benhylau** [comment]
>To post a message to all the list members, send email to compost@lists.hypha.coop. 

See https://lists.hypha.coop/cgi-bin/mailman/listinfo/compost

**Comment by maisutton** [comment]
I'd like to close this issue and start a new one called "Community Engagement Plan". I'd add tasks like:
- Plan frequency of mail updates
- Write style/voice guide for social media posts (so far it's just me being me but would be good to write that out I guess in case I get hit by a bus)
- Organize public engagement event??

**Comment by benhylau** [comment]
You can do this to keep a reference from the new one if you like and close this off:

🎟️ Re-ticketed from: #5
