### ISSUE TITLE
Decide on new HTTP API

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#52]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

Related to #43 and #41 

## Task Summary

We will be updating the HTTP API to change how DNS records are set up as well as account for more efficient publishing of changed files.

...

## To Do

- [x] Review existing 
- [x] Discuss needs with Sutty
  - [x] How will DNS work
  - [x] Registering domains
  - [x] Uploading tarball with just the changed files.
- [ ] Text description of new API
- [x] Document API with Swagger.json or similar
- [x] Auto-generate API docs?

**Comment by RangerMauve** [comment]
Only pending thing is how the DNS should work

**Comment by RangerMauve** [comment]
Our HTTP API is now pretty set in stone. :)
