### ISSUE TITLE
Update IPFS uploading code

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#53]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** DP sites can be configured with IPFS and can publish to IPFS/IPNS

## Task Summary

We'll need to review how we upload data to IPFS and see if there's stuff that cause use updating / changing. Particularly this might be needed to do efficient diffing of data.

We might also want to rework how pinning roots and publishing IPNS public key records should work.

## To Do

- [x] Investigate existing IPFS stack and update compoents
- [x] Create library to sync MFS with the filesystem (and vice versa)
- [x] Create IPFS Provider which uses MFS
- [x] Add ability to create sites with provider (create IPNS keys, etc)
- [x] Add sync functionality with IPFS provider
- [x] Link up code to invoke the provider
- [x] Add test for creating a site with IPFS and uploading data to it
- [ ] Load tests using js-ipfs-fetch
- [x] do a manual test to load a site published this way in Agregore

**Comment by RangerMauve** [comment]
Update on this, I've made a new API using js-ipfs (which can talk to Kubo) which uses the MFS (mutable filesystem) function for synchronizing to and from IPFS (and can apply efficient diffs instead of needing to upload everything each time.

https://github.com/RangerMauve/js-ipfs-mfs-sync

Now that this is in place I can start updating the code with an IPFS "Provider" which can sync folders to IPNS and manage the IPNS keys for a site.

**Comment by RangerMauve** [comment]
This has been added in the new protocols PR in api.distributed.press
