### ISSUE TITLE
Use UCANs for authentication

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#54]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

It would be useful to generate authentication tokens which can delegate permissions or have just a subset of permissions.

The [UCAN](https://ucan.xyz/) spec has this functionality in mind.

This probably isn't urgent, but we should take it into consideration.

...

## To Do

- [ ] Evaluate needs
- [ ] Issue auth tokens using UCAN
- [ ] Create tokens with subsets of permissions
- [ ] Have examples for delegating permission (need the auth token to sign a public key which will then sign more public keys?)

**Comment by sutty-coop** [comment]
Would we need to develop rb-ucan?

**Comment by RangerMauve** [comment]
This is going to be postponed for a while. We'll want to wait for the UCAN spec to settle down and figure out how it'll get implemented in sutty.

I'm also gonna be doing some UCAN work for WebRecorder so I'll have a better picture at that point.

**Comment by RangerMauve** [comment]
Not part of current roadmap. Will revisit at a later date if we find we need it.
