### ISSUE TITLE
Set up initial project structure

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#57]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** We can run tests and run the "index.ts", basic folder structure is figured out  

## Task Summary

We'll set up the project structure for the new version of the site.

## To Do

- [x] new branch
- [x] Move existing code to `v0` folder
- [x] Set up a `v1` folder
- [x] Set up typescript and package.json scripts to run everything
- [x] Set up linting with either [standardjs](https://standardjs.com/) or an equivalent.
- [x] Sketch out the HTTP API based on the planning docs (with fastify)
- [x] Sketch out the modules based on the planning docs
  - [x] config
  - [x] publisher
  - [x] authorization
  - [x] dns
- [x] Set up unit tests, e.g. with [ava](https://github.com/avajs/ava)
- [x] PR into the [v1](https://github.com/hyphacoop/api.distributed.press/tree/v1) branch

Once we use this we'll start working on module implementations and tests
