### ISSUE TITLE
Set up config with LevelDB

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#58]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We'll need to have a module for storing configs about accounts + sites in DP.

To do the actual storage we'll make use of leveldb and the levelup ecosystem since it's efficient for local storage but can scale up to different backends if we need it to (e.g. redis, postgres, etc).

This is also needed to be able to store and resolve authentication

...

## To Do

- [x] Research LevelDB and the levelup ecosystem
- [x] Set up the `Config` class to initialize the db and pass instances to subclasses
- [x] Implement the methods for storing / retrieving / updating configs
- [x] Add tests for all the methods
- [x] PR into v1 branch
- [x] Review
- [x] Merge!
