### ISSUE TITLE
Set up initial authentication/authorization system

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#59]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Depends on #58 

We need a method to authenticate calls to our API endpoints.

Eventually we'll be migrating to UCANs once they've stabilized, but in the meantime we need something more simple.

After the initial auth flow, we'll look at how to create JWTs with scoped permissions. E.g. it's a token for a publisher, but it can only publish to one site and for a particular file path within.

## To Do

- [x] Investigate using jwt with fastify, or setting up our own bearer token strategy (using jwt)
- [x] Create API for generating auth tokens
- [x] Add auth to HTTP endpoints (admin and publisher)
- [x] Figure out how to do refresh and document it
- [x] Create CLI (or something) for generating initial JWT keypair
- [x] Ensure auth is captured in swagger endpoint
- [x] Add tests for creating auth tokens / using them (include tests to check that no auth token or invalid auth token results in an error)
- [x] PR into v1
- [x] Merged

**Comment by RangerMauve** [comment]
We had a call to talk about auth with Jacky and Fauno. Basically we wanted to get on the same page about JWT token expiration / generation and how to pass them around. The TLDR is that we'll use JWT tokens for authenticating publishers and admins. To onboard a publisher an admin will create their account, then generate a token for them. Then the publisher can use that token with the API calls. Tokens expire so the publisher will need to refresh their token periodically which can be part of the client API.

So far we're not 100% sure what will actually go into the token, but it'll at least have the id of the publisher and the token expiration info.

Also not entirely clear whether we'll use bearer tokens or cookies, but I think we can figure that bit out async.

The main purpose of using JWTs is to start experimenting with tokens issues using public keys and to have a path to generate tokens with scoped permissions as UCANs start to become more mature and stable so that we can switch to them when the time comes more smoothly.

**Comment by fauno** [comment]
> Also not entirely clear whether we'll use bearer tokens or cookies, but I think we can figure that bit out async.

It's the same on the Ruby API client side because it's either header we add to the request.

It only matters on browsers because it will only attach the cookie for requests sent to its domain name, and the cookie can be out of reach of JS it's HttpOnly.  If I'm not mistaken, the cookie is set for the refresh token to talk to the authentication server and a JWT is a bearer token issued by this server to send to the endpoints that require authorization, who may not be under the same domain.

**Comment by RangerMauve** [comment]
That's a great point. TBH I would prefer bearer tokens instead of cookies if it's easy enough to do. 😁
