### ISSUE TITLE
Grants research

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#6]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have a list of grants we want to apply and a plan to apply for them.  

## Task Summary

Reseach more grants and put deadlines in calendar.

## To Do

- [x] Finalize branding and website (September 12) @uditvira -> ⛏️ dig deeper
- [x] Put together pitch deck (based on article @uditvira shared and GFTW + EF) @maisutton
    - content (September 18) @maisutton 
    - branded (September 22)
- [x] `2020 Q4` Go ahead with applications to:
    - [x] NGI Zero Discovery @benhylau (September 18 first draft in gdoc)
        - Social API work pitched, declined in final round
    - [x] EF @uditvira (moved to 2021 Q1)
- [ ] `2021 Q1` Investigate
    - [ ] `2021 Q1` [EF Ecosystem Support](https://ecosystem.support/)
    - [x] `2021 Q1` [NGI Zero Discovery](https://nlnet.nl/thema/NGIZeroDiscovery.html) (reapply for Feb 2021 call)
    - [ ] `2021 Q1` [Interchain Foundation](https://interchain.io/funding/)
    - [ ] `2021 Q1` [IPFS Grants](https://github.com/ipfs/devgrants#open-grant)
    - [ ] [Web3 Foundation](https://web3.foundation/grants/)
    - [ ] [Chainlink](https://chain.link/community/grants)

**Comment by benhylau** [comment]
Come up with a list to discuss for next week.

**Comment by maisutton** [comment]
Pulling notes from our hackpad on potential funding sources:
- Cira
- Open Tech Institute
- Open Tech Fund
- Knight Foundation

People to talk to:
- Wendy Hanamura, Internet Archive
- Dan Gillmore, Knight Center for Digital Media Entrepreneurship

Institute for Nonprofit News (inn.org) links to [this spreadsheet with journalism awards](https://docs.google.com/spreadsheets/d/e/2PACX-1vQQtnIcrVpgQ8fbjzUzl0j-yQaCF_2iRnAuoI8drF9X1VtQI9drM9up5rR6COma0Gqz1PnOohiv-45R/pubhtml?gid=737971653&single=true).

**Comment by benhylau** [comment]
- Knight Center for Digital Media Entrepreneurship
- Ethereum Foundation
- Internet Archive
- IPFS https://github.com/ipfs/devgrants#open-grant
- Knight Foundation https://knightfoundation.org/programs/journalism/
- https://p2pfoundation.net
- https://ledgerproject.eu
- https://nlnet.nl

**Comment by benhylau** [comment]
## TODO

1. Finalize branding and website @uditvira 
2. Put together pitch deck (based on article @uditvira shared and GFTW + EF) @maisutton 
3. Go ahead with applications to:
    - NGI Zero Discovery @benhylau 
    - Knight Foundation @maisutton 
    - EF @uditvira (after pitch deck work)

**Comment by maisutton** [comment]
Knight Foundation - Submit an idea through their Fluxx portal, if they are intrigued they will then invite you to submit a full proposal: https://knight.fluxx.io/lois/new?utf8=%E2%9C%93&commit=Apply+Now

Fields
- Name (first, last)
- Email
- Org legal name
- Program (journalism, arts, etc)
- Relationship Manager at Knight Fdn
- Amount requested
- Impact: What results do you expect to achieve? (250 chars max)
- Use of funds: How will you use KF Funds? (750 chars max)

**Comment by benhylau** [comment]
NGI Zero grant submitted.

**Comment by benhylau** [comment]
Added a bunch of new grants to top issue for `2021 Q1`
