### ISSUE TITLE
Sketch out flow for "disabling" without "deleting"

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#61]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

...

## To Do

- [x] Add API to protocol backends to "stop seeding"
- [x] Ensure we can disable protocols when updating
- [ ] Document flow for sutty to disable vs delete sites.
