### ISSUE TITLE
Implement raw storage for sites

### ISSUE THREAD

**Issue by jackyzha0** [hyphacoop/distributed-press-organizing#62]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Currently, the `/sites/:id` endpoints for uploading files are just stubs. Fully implement these features.

## To Do
- [x] Parse files and ensure within reasonable bounds (i.e. no 1TB sites)
- [x] Read config and trigger appropriate p2p providers (see `protocols/interfaces.ts`)
- [x] Add a way to configure the "storage folder" where the raw files will be stored for sites
- [x] Have the upload endpoint add those files to the respective sites folder
- [x] Add tests for various example site payloads
- [x] PR into v1
- [ ] Merge

**Comment by jackyzha0** [comment]
Questions: how will admins get visibility into the status of the sites (e.g. storage used, seeding status, etc.)? Should we add API endpoints for these?

**Comment by benhylau** [comment]
Discussed at call.

I think if it's easy, we can put an endpoint and document the schema, then Sutty can scrape the endpoint in their next milestone and make pretty visuals of these data.

In the current milestone they should focus on COMPOST theme port and MVP features.

**Comment by RangerMauve** [comment]
Good catch, mind creaating a new issue to track this feature? We can figure out which milestone it should go into later. 👍

**Comment by fauno** [comment]
We would be hosting the raw sites but we can add the Distributed Press IP addresses on the rotation
