### ISSUE TITLE
Record end to end demo for FFDW

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#63]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Feb 2023
🎯 **Success criteria:** ...  

## Task Summary

We're planning to do an internal end to end demo of using Sutty to publish to DP.

Once we have that working, it'd be useful to do a clean recording of that in action which we can share around to FFDW and the such (maybe even on our website?).

## To Do

- [ ] Prep end to end demo with sutty
- [ ] Do a screen recording
- [ ] Run by somebody to see if we can clean the audio or recording
- [ ] Upload somewhere (via sutty? :P)
- [ ] Send to Brynn

**Comment by RangerMauve** [comment]
My initial thoughts for script:

Sutty Demo:
- Open sutty panel
- Make new site
- Select template
- Add post to homepage
- Enable dweb publishing in settings
- Publish site
- Visit p2p version of site

Github Actions Demo:
- Make repo on github
- Eanble github pages
- Load HTTPS version
- Show adding token to env vars
- Add github action
- Show how it publishes
- Copy over p2p URL and load it
- Add DNS NS record to point to DP
- Show p2p URL with DNS for content

**Comment by fauno** [comment]
We can go ahead with this after #44 unless you want to demo another theme.

**Comment by RangerMauve** [comment]
I think we had done this?
