### ISSUE TITLE
Ensure DNS works

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#65]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We should add unit tests for our custom DNS server to verify that it's all working

...

## To Do

- [x] Scaffolding for DNS server unit tests
  - [x] Start a DNS server in memory with just the site data
  - [x] Use the DNS module to query it directly
- [x] Create a site and try to resolve the TXT entry
- [x] Add failing test to make sure unknown domains aren't resovled, or non txt records
- [x] #66
  - [ ] Get elon's help to set up a NS record on one of our domains
  - [ ] Maybe set up a domain for the DNS server to use for the NS record
  - [ ] Test querying the DNS server via a CLI tool like dig 
- [x] Test resolving sites using real DNS and manual testing
- [ ] Test sutty DNS resolver with our DNS server with a subdomain
- [ ] ipns resolve works on public gateways
- [x] ipns resolve works in agregore
- [x] hyper resolve in agregore works

**Comment by RangerMauve** [comment]
THis is working now, remaining tests are going into #68
