### ISSUE TITLE
QA test P2P protocols

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#68]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We should test loading published sites in different environments:

## To Do

- [x] IPFS Agregore (very slow)
- [x] IPFS ipfs.tech gateway
- [x] IPFS in our gateway
- [x] IPFS in web3.storage gateway
- [ ] IPFS in Brave
- [ ] IPFS in Opera
- [x] Hyper in Agregore
- [x] Hyper in our gateway

**Comment by benhylau** [comment]
| Browser | Hypercore | IPFS | IPNS |
|:--------|:--------|:--------|:--------|
| Agregore Desktop | | |
| Agregore Android | | |
| Agregore iOS | | |
| Brave Desktop | | |
| Brave Android | | |
| Brave iOS | | |
| Opera Desktop | | |
| Opera Android | | |
| Opera iOS | | |
| Chrome Desktop + IPFS extension | | |
| Firebox Desktop + IPFS extension | | |

**Comment by RangerMauve** [comment]
Loading is at least working on gateways now, usually after an initial reload. Tomorrow Yurko and I will look into how we can speed it up on our personal gateway with ipfs-cluster.

**Comment by RangerMauve** [comment]
After our most recent round of IPFS optimization all the gateways are loading our data way more reliablyy. 🥳

**Comment by RangerMauve** [comment]
I think our performance has gotten to a point where we can close this. Feel free to re-open if we need to do another round.
