### ISSUE TITLE
Create Github Action for publishing to DP

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#69]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We should add a new github action and publish it to the marketplace

## To Do
- [x] Add step to turn a folder (configured by a variable) into a tarball
- [x] Use HTTP request with authentication (configured by an env variable) to upload the tarball (site should be a variable
- [x] Test!
- [x] Add the ability to auto-create a site if it doesn't already exist
- [x] Test again!
- [x] Docs on how to use it and an example repo

**Comment by jackyzha0** [comment]
I'm guessing it will default to DP staging?

**Comment by RangerMauve** [comment]
Yeah, but I think we can aim to release to prod before we merge the PR

**Comment by RangerMauve** [comment]
This is done!
