### ISSUE TITLE
COMPOST website on DWeb

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#7]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Jan 18, 2021  
🎯 **Success criteria:** Put COMPOST website on WWW, IPFS, HYPERCORE.  

## Task Summary

Publish COMPOST site on `staging.compost.digital` then `compost.digital`.

Publish COMPOST api on `api.staging.compost.digital` then `api.compost.digital`.

## To Do

- [x] Set up Nginx files for WWW @ASoTNetworks 
  - ~Map `<project.domain>/` -> `distributed.press/compost/` and verify SSL certs~
  - ~Map `api.<project.domain>/` -> `api.distributed.press/compost/` and verify SSL certs~
  - [x] Map `<project.domain>/` -> `~/.distributed-press/data/projects/staging.compost.digital/www/` and verify SSL certs
  - [x] Map `api.<project.domain>/` -> `~/.distributed-press/data/projects/staging.compost.digital/api/` and verify SSL certs
- [x] Publish on IPFS
- [x] Publish on Hypercore
- [x] Verify that site and api work according to the URLs in the [spec](https://github.com/hyphacoop/api.distributed.press#api-specifications)
- [x] Update content to display DWeb URLs

**Comment by benhylau** [comment]
@ASoTNetworks you can publish this site if you like to test our #17

**Comment by benhylau** [comment]
**IPFS** more or less works now, aside from some subdomain-based gateway/Opera Android issue that IPFS is already investigating. See bottom right of the footer here, it's working https://ipfs.io/ipns/staging.compost.digital

For **Hypercore** pinning, it's "code complete" but somehow dat-store doesn't do what I expect it to do. Specifically:

- pinning the website just hung at [hyperdrive-publisher.sync](https://github.com/hyphacoop/api.distributed.press/blob/main/pinning-services/index.js#L43) (even tho the first time it showed the diff) you'll see that the archives aren't available
  - https://hyper.distributed.press/eae46fb25b88cfd1b8cd2bb7e45584d9f1170065422dbfab05adade945f22b20/
  - https://hyper.distributed.press/staging.compost.digital
- the gateway returns stale data https://hyper.distributed.press/api.staging.compost.digital/monetization (balances.json should be there)
- the `dat-store` CLI is always hung now, and I have tried wiping urls manually, but publishing the site seems to break it

Aside from this, the last couple commits I made to https://github.com/hyphacoop/compost.digital contains some learnings about how to design dweb compatible websites. @bennlich we should sync up in Jan about this, mainly relating to paths and ending files with .html

cc. @ASoTNetworks @rangermauve

**Comment by benhylau** [comment]
On IPFS, even though `bafybeigks5khlraols4otk3n4nlcipzphyjxpkbgfboiihby5rkjc75aqm` is available on our server and ipfs.io, I can't seem to get it on some other servers with `ipfs get bafybeigks5khlraols4otk3n4nlcipzphyjxpkbgfboiihby5rkjc75aqm` and public gateways.

**Comment by benhylau** [comment]
>- pinning the website just hung at hyperdrive-publisher.sync

This is fixed temporarily with a long sync timeout, and filed https://github.com/RangerMauve/hyperdrive-publisher/issues/8#issue-775220168 for hypercore-publisher to implement a long-term fix.

Hopefully this also addresses the other two hypercore problems above.

**Comment by benhylau** [comment]
All the links [in this spec's example](https://github.com/hyphacoop/api.distributed.press#api-specifications) are now working 🚀

**Comment by bennlich** [comment]
@benhylau Should these links work?

https://ipfs.distributed.press/ipns/api.staging.compost.digital/v0/monetization/balances.json
https://hyper.distributed.press/api.staging.compost.digital/v0/monetization/balances.json

I got them from https://github.com/hyphacoop/api.distributed.press#monetization-api
