### ISSUE TITLE
QA Test with Sutty

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#70]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Mar 28th 
🎯 **Success criteria:** We have tested all the sutty features we expect to be used and most of the main issues are ironed out

## Task Summary

We'll go off of what Sutty put together for QA and follow up.
They're doing an initial pass so we'll add tasks here once we know better.

Sutty side here: https://0xacab.org/sutty/sutty/-/issues/?search=QA&sort=updated_desc&state=opened&in=TITLE&first_page_size=20 and https://0xacab.org/sutty/sutty/-/issues/?search=QA&sort=updated_desc&state=closed&in=TITLE&first_page_size=20

...

## To Do

- [ ] Sutty will do intial testing
  - [x] QA test issues written
  - [ ] QA tests all performed
  - [ ] Found bugs fixed
- [ ] Hypha will test from the perspective of a new user
  - [x] New user visiting the Sutty home page
  - [x] Account creation
  - [x] Password reset
  - [ ] Site creation (minima template)
  - [x] Inviting guest editors
  - [x] Creating post in Spanish side
  - [x] Creating post in English side
  - [x] Text editing for post content
  - [x] Image uploads
  - [x] Post cross-linking
  - [x] Publishing
  - [ ] Dweb publishing
  - [ ] TODO: Other templates
- [ ] Hypha will add issues to Sutty's issue tracker
  - [ ] Issues with text description and reproduction steps
  - [ ] Screenshots
- [ ] Final pass to see that sutty with DP is usable

**Comment by RangerMauve** [comment]
- Would be nice if there was an obvious way for the first page to link to a "get started". Not clear what Sutty is or how to use it
- Also, hard to find the "English" button when you first navigate, and not obvious whether there even is one
- Can bar be at the top with all the important buttons like "Make an account"?
- On MacOS with Firefox the scrolling "jump" doesn't work correctly. COuld it be removed or could there be something added to fix the MacOS experience
- Works on Linux Chromium
- Maybe use position: stick for the top bar?

**Comment by RangerMauve** [comment]
- Get your site doesn't take your local into consideration. The EN link should link to the EN version of the sign in page.
- Would it be possible to detect your local from the user agent and auto-redirect? Or does that conflict with spanish uses?

**Comment by RangerMauve** [comment]
- Password reset email isn't in English
- The link is also not in English when pressed
- After log in the correct language preference is loaded

**Comment by RangerMauve** [comment]
- Ben was unable to log into Sutty with his account

**Comment by RangerMauve** [comment]
- Would be nice if we could have an english-only (or other language-only) version of the panel to link to folks.
- Maybe the local can be in the subdomain or the path?

**Comment by RangerMauve** [comment]
- Would be nice if there was a "Here's the features and how to use them" guide somewhere
- Unclear how to use it just by logging into the panel

**Comment by RangerMauve** [comment]
- Published site should default to your prefered language or have both on the default page
- Currently defaults to Spanish

**Comment by RangerMauve** [comment]
Would be good if when publishing posts you could default to your preferred system language instead of spanish

**Comment by RangerMauve** [comment]
- When typing in the post content text box, if selecting all and deleting, unable to type after unless you click into the box again.
- Seems like the big white rectangle isn't actually the full text area. Is it a contenteditable bug?
- There's no "undo" option, so if we make a mistake there's no going back. Might be a MacOS/Firefox. Should make sure to sue the correct keybindings or check on Mac.

**Comment by RangerMauve** [comment]
- In the content editer, when selecting a file to upload, there's no indication that the file got selected, but hitting upload uploads the file as expected
- There should be an indication on the file upload thing to say that the file was uploaded
- Can't add description for the image description before clicking upload
- Would be good to be able to type in the box before hitting upload, or not showing the box until after hitting upload

**Comment by RangerMauve** [comment]
- No clue about how to rearrange the order of post contents, like can an image be moved up or down between paragraphs?

**Comment by RangerMauve** [comment]
What is the "Castillian Spanish" section of the post editor for? In the English version the drop down gives you something in spanish and it's not clear what the options are for

**Comment by RangerMauve** [comment]
- When linking to the alternate language version of the post, it doesn't  seem to do a bidirectional link

**Comment by RangerMauve** [comment]
- benedict@hypha.coop is no longer accessible with password, even with password reset, can DM the password on request (maybe you can try it?)
- It could be a character encoding issue: `tell#sync0`

**Comment by RangerMauve** [comment]
- No indicator of how long publish will take or what the status is. Had to periodically refresh the site until it worked.

**Comment by RangerMauve** [comment]
- In the "minima" template, there was two posts added in Spanish by default
- They don't show up in the posts list and there's no clear way to delete them

**Comment by RangerMauve** [comment]
- There's no link to English version of the site from the "posts" page in Spanish (in minma theme)

**Comment by RangerMauve** [comment]
- Tags and catagories didn't show up in the UI in the posts list or when clicking on the post directly (in minima theme)

**Comment by RangerMauve** [comment]
Post image that got uploaded is missing from the post when viewing it on the site or within the content in the panel (edit / view)

**Comment by RangerMauve** [comment]
TODO on testing:
- Test other themes
- Test DP (can we see links yet?)

**Comment by fauno** [comment]
> Test DP (can we see links yet?)

when you publish changes you get an email with all the links

**Comment by RangerMauve** [comment]
> > Test DP (can we see links yet?)
> 
> when you publish changes you get an email with all the links

Excellent. Would also be nice to see those links either in the templates or in the panel somewhere (ideally both if possible?)

**Comment by fauno** [comment]
@benhylau @RangerMauve 

I've created issues on our repo, but I need to ping you for details in some of them, could you send me your 0xacab users?  Otherwise _I think_ I can give you some email addresses to follow them as email threads.

**Comment by fauno** [comment]
Updates:

* We went through the CMS and reported and prioritized issues
* Most of them are fixed and others are being tested
