### ISSUE TITLE
Deploy DP to production

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#71]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** 2023/03/24
🎯 **Success criteria:** We have a new "production" VM generated  

## Task Summary

We're just about stable enough to do a deployment of Distributed.Press to Production at api.distributed.press.

This will involve migrating our existing data over to a new VM then updating all the DNS settings once we've verified that data is loadable.

...

## To Do

- [x] Identify existing resources @YurkoWasHere has a hackmd
- [x] Set up new prod VM with DP (based on ansibles)
  - [x] ~~DO~~ or Montral VM?
  - [x] @YurkoWasHere will get me SSH access to the VM
  - [x] Generate key and store admin credential somewhere
  - [x] Set up publisher keys for compost/hypha/DP itself
- [x] Set up temporary DNS for it
- [ ] Publish compost (via sutty?)
   - [x] one.compost.digital
     - [x] Add GH action: https://github.com/hyphacoop/one.compost.digital
     - [x] Merge https://github.com/hyphacoop/one.compost.digital/pull/31
     - [x] Test
   - [x] two.compost.digital
     - [x] Add GH action https://github.com/hyphacoop/two.compost.digital
     - [ ] Merge https://github.com/hyphacoop/two.compost.digital/pull/94
     - [x] Test
   - [ ] three.compost.digital
     - [ ] Published via Sutty
     - [ ] Test
   - [ ] compost.digital (is this a redirect?)
- [ ] Publish distributed.press landing page
  - [x] Replace Travis with GH action https://github.com/hyphacoop/distributed.press/blob/master/.travis.yml
  - [x] Replace Travis with Sutty CMS
  - [ ] Review and update text: link to docs page and add CONTACT US prominently at top
  - [x] FAILED -- Merge https://github.com/hyphacoop/distributed.press/pull/14
  - [x] Test
- [x] Publish distributed.press docs cc @jackyzha0 (via the doc generator we're going to use #67 )
- [ ] Publish Hypha hompage
  - [x] Add GH action https://github.com/hyphacoop/hypha.coop/blob/master/.github/workflows/deploy.yml
  - [x] Merge PR https://github.com/hyphacoop/hypha.coop/pull/190
  - [x] Publish to staging
  - [x] Publish to Prod
  - [ ] Test
- [ ] Update DNS to point to the new prod instance
  - [x] distributed.press
  - [x] docs.distributed.press
  - [x] one.compost.digital
  - [x] two.compost.digital
  - [ ] three.compost.digital
  - [x] compost.digital
  - [x] hypha.coop
- [x] Update ansible to add HTTP file serving via Nginx for our prod domains
- [x] Github action release
 - [ ]

**Comment by benhylau** [comment]
Couple questions on migration:
1. I think we should keep publishing `one.` and `two.` of COMPOST via existing repos' GH Actions, not via Sutty.
2. Will Hypercore keys change for existing published sites? I think it's ok for them to change since they never really worked anyways, they were published via Beaker and pinned. No need to spend extra effort to preserve keys other than changing GH Action to use new instance.
3. Will IPFS CID and IPNS change after changing instances? I imagine no, since IPFS should hash the same, and IPNS is just a DNS TXT record to that CID.
4. I see other than two issues of COMPOT, we are also migrating hypha.coop, do we need to also migrate staging.hypha.coop and the sutty site on there? Any other site?
5. After this are we shutting off current prod instance?

**Comment by RangerMauve** [comment]
The new VM is up, we've got docs.distributed.press on it.

Next steps will be to migrate all our other domains to publish there with the new github action and switch over DNS. I've got DNS access now so I can just take care of the final bits. Huge thanks to Jacky for getting the Github action and initial workflow stuff working for staging version of docs!

**Comment by RangerMauve** [comment]
> 1. I think we should keep publishing `one.` and `two.` of COMPOST via existing repos' GH Actions, not via Sutty.

Agree! Will update the actions to use the new DP publish action however

> 2. Will Hypercore keys change for existing published sites? I think it's ok for them to change since they never really worked anyways, they were published via Beaker and pinned. No need to spend extra effort to preserve keys other than changing GH Action to use new instance.

Yes, hypercore keys will change since the new version of hypercore (holepunch) is incompatible with the old format. The domains will be the same and people using Agregore will be able to load it seamlessly.

> 3. Will IPFS CID and IPNS change after changing instances? I imagine no, since IPFS should hash the same, and IPNS is just a DNS TXT record to that CID.

I'm not sure because it depends on whether we have the same IPFS add settings as before. I'm thinking it'll be totally different since we have a new version of IPFS. As well, DNS is fundamentally different because before we were publishing an IPFS CID to the DNS record whereas now we're publishing an IPNS key (this lets us do updates almost instantly and avoid DNS update propagation issues)

> 4. I see other than two issues of COMPOT, we are also migrating hypha.coop, do we need to also migrate staging.hypha.coop and the sutty site on there? Any other site?

Defs migrating hypha.coop to new prod.

I'm not sure about staging.hypha.coop, would appreciate opinions here. It could be useful to have staging.hypha.coop use the new chanterelle staging DP instance so we can mess with breaking things and new protocols without affecting prod. The publish flow would be the same as prod just with a different URL and JWT

> 5. After this are we shutting off current prod instance?

I'm not sure. I think it would be good to shut it off to save on resources. We might want to make sure we're seeding the old CIDs/old hyper stuff somewhere however if we care about backwards compat (feels like we don't in this instance, though). Would love others opinions on this as well

**Comment by RangerMauve** [comment]
@maisutton Thoughts on the above?

**Comment by RangerMauve** [comment]
Updated TODO list with more details for the individual sites.

**Comment by RangerMauve** [comment]
I'm about to wipe staging and rebuild it in prep for the hypha landing page deploy

**Comment by RangerMauve** [comment]
Also, waiting for the three PRs for distributed.press and the one/two .compost.digital domains to get reviewed.

**Comment by RangerMauve** [comment]
Waiting on reviews before merging everything and testing the deploys

**Comment by maisutton** [comment]
Considerations
* FFDW milestone deliverables
* COMPOST release and contributor participation

Release
* Rolling release
    * 1 - Github action
        * Docs are published but needs review
            * Andi?
        * Reach out to FFDW groups
        * DP site build needs to be fixed
            * Strip down the DP landing page
            * Landing page to point to docs site
            * CONTACT US at the very top
        * Static site published >> any data available on the protocols
        * Pricing for onboarding work
            * $1-2 K for each onboarding
            * Scope it - effort for them to do it vs. using our tools vs. us doing it
            * Save money and achieve goals that you'd have a hard time doing otherwise
        * TO DOs
            * Scope of the product - tasks -- (self-hosted vs. we hosted), level of data, support contracts (how much automated, availability to debug); one-time set-up, call us for support 
            * Pricing
        * PROMOTION
            * Uber hackers who can set it up themselves
            * Everyone else talks to us for set up
    * 2 - Sutty CMS
        * Soft release, it can be used to publish to DP but needs onboarding at the moment
        * Needs to be hands on, get feedback directly
        * VERY prominent place for feedback
        * Contact us for deployment or follow it yourself, might be hard and please give us feedback

TO DOs
* Add this to do to prod release Github
* Scope of the product - tasks -- (self-hosted vs. we hosted), level of data, support contracts (how much automated, availability to debug); one-time set-up, call us for support 
* Price out services and review by Hypha
* Finalize review of docs page
* Draft an email to FFDW laying out our plans
* Discuss on Thursday April 12 all-hands

**Comment by RangerMauve** [comment]
[one.compost.digital](http://one.compost.digital/) [two.compost.digital](http://two.compost.digital/) [api.distributed.press](http://api.distributed.press/) and [distributed.press](http://distributed.press/) have been migrated

Distributed.press is now being managed by sutty since the github action couldn't get the ruby dependencies working

**Comment by RangerMauve** [comment]
Latest updates is #76 tl;dr announcement on Tuesday.

**Comment by RangerMauve** [comment]
Deployed staging.distributed.press

Going to test it out real quick then do the same with prod

**Comment by RangerMauve** [comment]
This is fully done!
