### ISSUE TITLE
Write technical documentation for Distributed Press

### ISSUE THREAD

**Issue by jackyzha0** [hyphacoop/distributed-press-organizing#72]
## Task Summary

We should have documentation so that new users to Distributed Press can get setup easily

## Docs to write
- [x] Non-technical Overview (what does Distributed Press actually do?)
- [ ] Technical documentation 
	- [x] Overview (what are the parts of Distributed Press?)
	- [ ] Supported Protocols (maybe briefly mention how to contribute support for more protocols)
	- [x] API Server (API reference)
	- [ ] DNS Server (why we also deploy a DNS server alongside the API server and basics of dnslink)
	- [ ] Setting up your own Distributed Press instance
- [x] Deploying a site to DP
	- [x] Using Sutty (mention that this is fully managed)
	- [x] Using GitHub Actions (this will require self-hosting DP, link to appropriate page)
- [x] Meta documentation (how to update the documentation)
