### ISSUE TITLE
Post Release Demo Followup

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#73]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Demo published somewhere, people spoken to. At least one new group tried out DP.

## Task Summary

After we get #63 together we should follow up with folks on showing them the demo and setting them up as well as doing promo.

## To Do (not in order)

- [x] Get demo recorded
- [x] Dripline/Compost post
- [x] Mastodon/Twitter post
- [x] FFDW channel update
- [ ] Follow up on people that expressed interest or are interesting
  - [ ] (TODO add handles)
  - [ ] Samuel from unit.land
  - [ ] See if https://connecthumanity.fund/ is interested in collabing
  - [ ] Ask around in the FFDW projects: https://fil-foundation.on.fleek.co/hosting/FFDW-2022-Annual-Report.pdf
  - [ ] Are.na / cab
  - [ ] DWeb website

**Comment by maisutton** [comment]
Closed and remaining tasks moved to issue #110

**Comment by maisutton** [comment]
Closed and remaining tasks moved to issue https://github.com/hyphacoop/distributed-press-organizing/issues/110
