### ISSUE TITLE
Increase DNS record expiration

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#75]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

At the moment even though we have p2p protocols to make data less dependent on our server, we still have a depencency on the DNS server to be up and responding to queries.

We should leverage the caching within DNS to reduce the number of times peers would try to request DNS records from us in the first place and make the TTL as long as is feasible so that it can be available for offline uses.

We might also want to place a caching DNS server in front of DP so that if there's a server outage, the cached records may still be served.

Similarly we should see if there's a way to configure popular systems to cache DNS records for offline use more agresivly and write guides for others to follow.

## To Do

- [ ] Research DNS TTL and caching tradeoffs
- [ ] Update integrated DNS in DP
- [ ] Add caching DNS server in separate process or VM
- [ ] Guides for improving DNS caching on client-side

**Comment by fauno** [comment]
I'm not sure there's a nameserver daemon that just proxies, what you usually do is set them as secondary servers who perform zone transfers (IXFR/AXFR) from the primary (DP in this case).  And you can tell them to keep serving the zone some time after the primary is offline.

For instance I do this to serve some zones from home using `nsd` but set dns.he.net as a secondary server in case of power outages (things usually fail more expectacularly when your zone is missing from DNS)

**Comment by fauno** [comment]
I recently configured knotd as a "reverse proxy" for smaller ns servers, I can provide a configuration file for it if you want

**Comment by fauno** [comment]
We talked about increasing this to 7 days

**Comment by RangerMauve** [comment]
Set to 7 days!

**Comment by RangerMauve** [comment]
This was deployed
