### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#76]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We're going to do an initial release with a "happy path" for sutty and GH actions out.

While we do this, we'll be uploading all the content for compost on sutty and will be getting feedback on the compost theme from the compost writers. Once that's ready we'll be able to publish it EoMish.

## To Do

- [x] (tuesday 4/18) draft up announcement tonight, pr to Hypha.coop's dripline for review (mauve)
- [x] (wednesday 4/19) Draft up [sutty](https://docs.distributed.press/deployment/sutty) docs with a "happy path" and pointers to where folks can ask for help (email sutty or contract them) (elio/mauve)
- [x] (wednesday 4/19) Edit deployment page blurb to have information about Sutty
- [x] (thursday 4/20) test out process of setting up a sutty blog w toggle + copyedit docs (mai)
- [x] (thursday 4/20) Check that dripline is able to publish to staging / prod (mauve)
- [ ] Test that emailing for support works
- [x] (friday 4/21) Finalize wording in announcement posts, get ready for merge (everyone?)
- [x] (monday 4/24) Merge PRs and check that the DP publish went through (mai or jacky?)
- [x] (monday 4/24) Fill out DP's Open Collective page (mai)
- [x] (monday 4/24) Draft social media posts + email content (mai / ania)
- [x] (monday 4/24) Check Sutty CMS -- magazine template "Coming soon"? (mai)
- [x] (tuesday 4/25) Send release package to FFDW, DWeb, and allies (mai)
- [x] (tuesday 4/25) Outreach to orgs + partners interested in testing (mai / mauve)
- [x] (tuesday 4/25) Post to Twitter/Mastodon for socials, mailing list (mai / ania)

**Comment by RangerMauve** [comment]
PR for Sutty docs https://github.com/hyphacoop/docs.distributed.press/pull/1

**Comment by RangerMauve** [comment]
I think this is all done too?

We should scope out the release for the compost specific bits next.
