### ISSUE TITLE
Webring tracking issue

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#78]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We'll be adding some basic webring support to distributed press instances so that content can be discovered within the instance by others.

...

## To Do

- [x] #74 
- [x] Site settings option for opt into webring
- [x] Add opted in sites to the same API that admins use
- [x] Add flag at the DP instance to turn the direction listing stuff on or of (opt into on)
- [ ] Make a static HTML based landing page for the instance which lists all the sites (using JS?)
  - [ ] Have a new "static" folder in DP with static assets for the landing page
  - [ ] Serve files from there at the root of the site (`/`)
  - [ ] index.html should have JS in it which pulls from `/v1/sites/`
  - [ ] Render the list as a `<ul>` with `<a>` links
- [ ] Update documentation (docs.distributed.press)
  - [ ] Add new section on the Webring functionality
  - [ ] Describe purpose and how to enable it for sites
- [ ] Publish and release
- [ ] Call to discuss more advanced UX on the 15th
- [ ] Mock up new UI
- [ ] Implement in the site
- [ ] Publish and release!

**Comment by maisutton** [comment]
The way we design the web ring views might be a great candidate for feedback from current and former COMPOST contributors, as well as Sutty CMS users! We could create a simply survey form with different options for how they might look and see what they think would be ideal.

**Comment by RangerMauve** [comment]
Added some more details to the issue based on what @maisutton  and I discussed today

**Comment by RangerMauve** [comment]
this is going to be put on hold while we figure out the details of the ActivityPub implementation. so far just being able to list of public sites is already available at the API level
