### ISSUE TITLE
BitTorrent tracking issue

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#79]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

BitTorrent is a popular protocol with a large ecosystem of clients and indexers for loading data.

We can work with this by getting sites published to BitTorrent and giving users the ability to share the magnet link or `bittorrent://` URL around.

This is also an opportunity to spread the use of "mutable torrents" which lets torrents update data over time.

This is one of the protocols supported in Agregore so users will have an immediate way to load sites (on desktop) and can also use standard torrent clients from the magnet link
...

## To Do

- [ ] Add BitTorrent protocol based on bt-fetch
- [ ] Add magnet links to P2P protocols list
- [ ] Add `bittorrent://` protocol to magnets list
- [ ] Get WebRTC webtorrent working
- [ ] Add tests for publishing
- [ ] Test with a WebTorrent browser client
- [ ] Add DNSLink for resolving torrents into Agregore
- [ ] Add docs on how to use it
