### ISSUE TITLE
activity pub integration tracking

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#80]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

this will be tracking the activity pub integration for milestone 2.

 the summary is that we will be creating a new server which will act as a service that publishes to distributed press. the server will speak the activity pub protocol for receiving notifications from other activity pub servers when there's a new comment or follow or some such.

 web sites published to distributed press  will incorporate  metadata into their page which will  link to their activity streams for the post.  they will also need to set up paths for web finger so that services like mastodon can resolve author names and tag them in replies.  this is still a little bit of a gray area and we'll need to run some experiments to see if it's even possible.

as replies are made to posts, they will be collected into a moderation queue. from there they can be approved or denied. if they are approved they will be collected  in activity streams represented as JSON which will then be published back to the website.

from here web sites can either load those things at runtime using javascript and render out responses, or the social server we'll send out a web hook to trigger a rebuild of the site.

we may need to be a little careful on how we can pull that data back in to build processes from the published site.

 another component we will need to  consider his how static sites can leave comments on each other.  ideally we should have some way of letting site authors tag posts as being replies to you or else of other posts. the social server will then need to pull those you are else and the post content and generate an activity pub  response to send to be in boxes of whatever thing was commented on.  if we focus on making use of  activity pub primitives these posts can seamlessly respond either to other static sites or to any other activity pub enabled service.

one thing that might give us trouble is figuring out how to set the proper content types for the activity stream and the web the finger data.

AP implementations to test compat with:
- [calkey](https://calckey.org/)
- [mastodon](https://joinmastodon.org/)
- [bonfire](https://bonfirenetworks.org/)

...

## To Do

- [x] Figure out moderation needs #77 
- [x] Static site example with webfinger (multi account?)
- [x] Static site example with activitystream of posts / replies.
- [x] Find way to resolve static post url to AP json
- [x] create new social.distributed.press repo
- [ ] add activitypub inbox to DP social
- [ ] add ability to register new inboxes for sites with JWT  authentication
- [ ] add api for notifying social of newly published post
- [ ] add follow support to social inbox
- [ ] send followers new posts
- [ ] add reply support to inbox with ap publishing
- [ ] moderation queue api
- [ ] block and allow lists with keywords
- [ ] instance wide vs site wide moderation

**Comment by maisutton** [comment]
Love that we decided to go with ActivityPub over Web Mentions as it allows us to meet communities where they already are. When we were discussing yesterday, the main thing that helped this all click together in my mind were a few things:
- That Distributed.Press sites could (or would?) itself be a Fediverse user, enabling them to post/interact with people as its own entity
- That posts on a DP site could be posts on the Fediverse itself -- Ex. an entire post could be viewed on Mastodon and 
- That Mastodon (or other ActivityPub implementation) could itself be the "comment section" where people engage with posts where they already are, and that the owner of sites could selectively curate the discussions onto the page as well, using the social server (pretty sure I have that right)

I understand that we have a lot of experimenting to see how these pieces fit together and interact on the back end, but we should bring in some expert UI/UX designers, like Super Bloom, early in the process to help us map user flows and user stories as the infra is being built.

**Comment by RangerMauve** [comment]
Relevant for resolving posts to their AP stream: https://github.com/w3c/activitypub/issues/310

**Comment by samuk** [comment]
Would you be interested in testing against the https://activitypods.org/ implementation too? I think it's one of the more interesting activitypub projects, although it doesn't get much press.

**Comment by RangerMauve** [comment]
@samuk Yeah sure! What sort of tests should we run against it? See if it can see our data and if users can respond to posts on it?

**Comment by samuk** [comment]
Yes that was what I was thinking.

**Comment by RangerMauve** [comment]
Would you be interested in us reaching out when we get to that point? I'm not sure if I'd want to host another thing just for the tests so working with folks that already run an instance would be easiest.

**Comment by samuk** [comment]
Yes, sure.

**Comment by RangerMauve** [comment]
Seems the meta tag stuff is already supported in calkey and mastodon so we can test with that in mind! 🥳

**Comment by RangerMauve** [comment]
Fruitful conversation with Boris from Fission

<spoiler>

```
2:49 PM]Mauve: Folks interested in this can comment on here or DM me: https://github.com/hyphacoop/distributed-press-organizing/issues/80#issuecomment-1564403722
GitHub
[activity pub integration tracking · Issue #80 · hyphacoop/distribut...](https://github.com/hyphacoop/distributed-press-organizing/issues/80)
🎟️ Re-ticketed from: # 📅 Due date: N/A 🎯 Success criteria: ... Task Summary this will be tracking the activity pub integration for milestone 2. the summary is that we will be creating a new server ...
activity pub integration tracking · Issue #80 · hyphacoop/distribut...
[4:05 PM]boris: @Mauve I have some money set aside for this already
[4:06 PM]boris: See https://opencollective.com/fission/contribute/ipfs-media-support-for-mastodon-48315
[Fission - IPFS Media Support for Mastodon - Open Collective](https://opencollective.com/fission/contribute/ipfs-media-support-for-mastodon-48315)
While ActivityPub federates messages and accounts, media attachments of images, audio, video, and other file attachments don't move in the same way.

This will initially focus on adding IPFS storage of media to the Mastodon / Hometown codebase, so that …
Fission - IPFS Media Support for Mastodon - Open Collective
[4:51 PM]Mauve: Ah! This is actually a bit different from what we're doing in DP. The DP code is to be an alternative to Mastodon which publishes AP data to IPFS instead of having a server storing that data.
[4:53 PM]boris: Yeah the wordpress and MicroDotBlog do something similar. I can’t really recommend it.
[4:53 PM]boris: Makes for a bad experience for everyone concerned.
[4:54 PM]Mauve: Oh is there a writeup that goes in more detail on that thought process?
[4:55 PM]boris: It has been me being an actual user 😉
[4:56 PM]boris: You can search for @boris@blog.bmannconsulting.com in Mastodon and it will find my MicroDotBlog
[4:56 PM]boris: No past posts are shown — you’ll only see it if you have notifications set or it happens to scroll by your feed
[4:56 PM]boris: No likes or post counts kept
[4:56 PM]boris: Commenting gets sucked into MicroDotBlog
[4:57 PM]boris: But of course as, say, a marketing user — it’s actually better to have a “real” company account that it cross posts to — so you can follow people, DM, etc etc
[4:57 PM]boris: I Switched to Masto cross posting so it ends up on my Boris@cosocial.ca account
[4:58 PM]boris: In my opinion, having first class AP accounts that a person can use with any client is the most valuable
[4:58 PM]boris: And cross posting would be a better goal for actual marketing users of a blog
[5:01 PM]Mauve: Interesting. Part of the goal with this integration is to move to not needing the AP server at all and to have able to focus on your IPFS data as being your first class identity which clients could pull from without needing an AP server in between you.
[5:02 PM]boris: Todays AP that would make for a shitty experience
[5:02 PM]boris: Like, yes, you might have post links of your own … but you already have that by publishing to IPFS
[5:03 PM]Mauve: Yeah, definitely. Current clients aren't geared for that use case at all. Also even if clients could access stuff from IPFS the AP spect itself is lacking indexing out of the box so it makes loading slower.
[5:07 PM]Mauve: Also to be clear, the AP integration in DP is less about cross posting to AP and more about using existing standards for social data like comments, with a goal of getting these standards to use more p2p tech in the future.
[5:16 PM]boris: I don’t think the AP architecture is a good fit for p2p at all
[5:17 PM]boris: Webmentions might be an easier lift here
[5:17 PM]boris: Which might work with a broader swath of things
[5:18 PM]boris: Eg you could do webmentions that consume AP or ATProtocol or other blogs etc etc
[5:18 PM]boris: IndieWeb has its own set of challenges here
[5:18 PM]boris: Anyway — will be interesting to see where you end up
[5:19 PM]boris: I have ~$3K in the open collective and need to talk to Sully or someone else with Rails / Ruby experience to integrate IPFS for media attachments in Mastodon
[5:21 PM]Mauve: Could you elaborate on what would be better about webmentions? As I understand it has a hard dependency on servers and there's no standard way to load posts or format responses (other than a URL?)
[5:21 PM]boris: If your goal is broad standards for comments
[5:22 PM]boris: Then supporting mentions calling back and being visible on the source blog post
[5:22 PM]boris: Is a useful feature
[5:22 PM]Mauve: Yeah that makes sense. Then we could have a moderation queue for folks to deal with how they want to bring those mentions back to their site content.
[5:22 PM]boris: Yep!
[5:22 PM]Mauve: It being a URL means there's less work for everyone on displaying it and scraping HTML becomes easier.
[5:23 PM]Mauve: Mind if I make a copy of this conversation for the GH issue where we're planning this?
[5:23 PM]boris: Go for it! Happy to jam on this
[5:23 PM]boris: I only have a vague notion of DP and it’s goals so I’m a little off the cuff here
[5:24 PM]boris: But I’ve been working on blogging and CMS systems for … some time 😉
[5:24 PM]boris: I’d love to a) promote DP
[5:24 PM]boris: And b) figure out some projects to do that overlap / integrate with some Fission stack stuff
[5:25 PM]boris: Ok and also I’m not going to abbreviate Distributed Publishing Press any more 
[5:26 PM]Mauve: Ah! I use DP to mean Distributed Press. Probably best to avoid acronyms TBH
[5:27 PM]Mauve: Yeah, I'll make sure to keep you up to date on this. Before getting to the comments we're going to be adding a simple "webring" feature to Distributed Press instances so that you can find content from other folks and form communities around instances.
[5:27 PM]boris: DistPress 🙂
[5:27 PM]boris: I think webring is awesome!
[5:27 PM]boris: Distributed Search
[5:27 PM]boris: I messed around with lieu for this
[5:27 PM]boris: https://github.com/cblgh/lieu
GitHub
GitHub - cblgh/lieu: community search engine
community search engine. Contribute to cblgh/lieu development by creating an account on GitHub.
GitHub - cblgh/lieu: community search engine
[5:27 PM]Mauve: Yeah if you have thoughts on webrings feel free to post them in this tracking issue: https://github.com/hyphacoop/distributed-press-organizing/issues/78
GitHub
Webring tracking issue · Issue #78 · hyphacoop/distributed-press-or...
🎟️ Re-ticketed from: # 📅 Due date: N/A 🎯 Success criteria: ... Task Summary We'll be adding some basic webring support to distributed press instances so that content can be discovered within th...
Webring tracking issue · Issue #78 · hyphacoop/distributed-press-or...
[5:28 PM]boris: I have a test install with Causal Islands speaker home pages and it's pretty fun!
[5:28 PM]boris: Goes back to stuff like "blog rolls" too
[5:28 PM]boris: Which again might be more of a fit for like WebSub and MicroPub https://www.w3.org/TR/websub/ -- but as you say, W3C URL / server centric a lot of the time....
WebSub
WebSub provides a common mechanism for communication between publishers of any kind of Web content and their subscribers, based on HTTP web hooks. Subscription requests are relayed through hubs, which validate and verify the request. Hubs then distribute new and updated content to subscribers when it becomes available. WebSub was previously know...
[5:29 PM]boris: thanks for all the links ... I'll poke around some more... off to a meeting!
```

</spoiler>

**Comment by silverpill** [comment]
@RangerMauve Regarding IPFS & ActivityPub: I've been thinking about this as well. One way to make AP objects content-addressable is to sign everything except the ID: https://socialhub.activitypub.rocks/t/use-cases-of-fep-8b32-object-integrity-proofs/3249/6.

**Comment by RangerMauve** [comment]
Update:  we have our initial static publishing experiment up  and are able to resolve the profile. https://mastodon.mauve.moe/@mauve/110674497488865824

 source code here: https://github.com/RangerMauve/staticpub.mauve.moe/

 next I will be experimenting with resolving posts to this profile and at the same time we will start working on our inbox implementation

**Comment by samuk** [comment]
I see your account from Kbin, https://kbin.social/u/@mauve@staticpub.mauve.moe

**Comment by RangerMauve** [comment]
@samuk That's great! I wish it loaded the posts from the outbox in the profile though. 🤔 I think Mastodon also has trouble with the initial load and only shows posts that you explicitly loaded from the user or that got POSTed to an inbox from the user's instance.

**Comment by RangerMauve** [comment]
Also, found another resource for how to structure posts: https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/

**Comment by RangerMauve** [comment]
Looks like ids *must* be full URLs. And it looks like Mastodon et al force us to make the HTTPS for now.

We can instead make use of [this FEP](https://codeberg.org/fediverse/fep/src/branch/main/fep/fffd/fep-fffd.md) to place additional URLs for data under the `url` property. (e.g. for the IPNS URLs or gateways)

https://mitra.social/objects/018944c5-3116-1433-e95e-e11b51a8e228

**Comment by RangerMauve** [comment]
It might be useful to make use of the `Article` ActivityPub type from Hometown for representing blog posts since it's more closely aligned with web page publishing.

https://github.com/hometown-fork/hometown/wiki/More-content-types

**Comment by fauno** [comment]
> It might be useful to make use of the `Article` ActivityPub type from Hometown for representing blog posts since it's more closely aligned with web page publishing.
> 
> https://github.com/hometown-fork/hometown/wiki/More-content-types

Mmm can it be both `Note` and `Article`? If `Article` is only supported by Hometown, it'll only be visible for their users, right?

Also what kind of markup does it support?  Does it support images/audio/video/iframe?

**Comment by fauno** [comment]
> Also what kind of markup does it support? Does it support images/audio/video/iframe?

The spec doesn't say much: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-article

**Comment by RangerMauve** [comment]
https://github.com/RangerMauve/staticpub.mauve.moe/issues/1

Related, we might want to add a host-meta file

**Comment by sutty-coop** [comment]
> Related, we might want to add a host-meta file

it's a static file, i already added it to the jekyll plugin

**Comment by RangerMauve** [comment]
xcellent, I meant adding it to my demo as well so folks can base their things on it

**Comment by RangerMauve** [comment]
AP integration is at a point where it's "working" so other things can be separate issues
