### ISSUE TITLE
Figure out pricing model

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#81]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

It would be useful to have some idea of how pricing for Distributed Press could work in the future. It likely isn't sustainable to just host everything for free, but if we intend to charge people for anything we should identify what they'd be paying for and why.

Quetions from Udit to get us started:

1. What are people paying for?
2. How are they paying?
3. Who do you imagine is a target user?

...

## To Do

- [ ] Identify pricing needs
- [ ] Do cost estimates
- [ ] Settle on pricing to offer folks

**Comment by sutty-coop** [comment]
Ideas for pricing and productization of Distributed Press are being discussed here:
https://docs.google.com/document/d/1sdFJ9aepkSZKSrw8SBVD-tqHAOuWchRGS89PHK9OsXo/edit?usp=sharing
