### ISSUE TITLE
Ansible nginx should redirect to https

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#83]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Currently if users load the http version of the api or a site, it'll stay that way. Some browsers still default to that which makes this a potential security problem.

NGINX has some standard methods for redirecting http to https, so we should add that in (maybe behind a flag?)

## To Do

- [ ] Add https redirect behind a flag
- [ ] deploy to staging and test
- [ ] deploy to prod

**Comment by sutty-coop** [comment]
i can share our nginx confs if you want

**Comment by RangerMauve** [comment]
Yeah sure :) I was thinking of looking at the ones letsecrypt uses, but any of them will do

**Comment by fauno** [comment]
Ok, let's see...

This is the Nginx config for all *.sutty.nl sites (except panel and API):

https://0xacab.org/sutty/ansible/sutty_panel_playbook/-/blob/antifascista/templates/wildcard.conf.j2

It uses a `$redirect_to_https` map to detect if it should immediately return a redirection to HTTPS:

https://0xacab.org/sutty/containers/nginx/-/blob/antifascista/nginx/maps/redirect_to_https.conf

The HSTS header tells browsers they should use HTTPS only from now on, so if you enter http://, they will rewrite to https:// without issuing an insecure request:

https://0xacab.org/sutty/ansible/sutty_panel_playbook/-/blob/antifascista/templates/wildcard.conf.j2#L19

The other headers are safety options
