### ISSUE TITLE
Remove js-ipfs from api.distributed.press

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#84]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

js-ipfs is being replaced by a new implementation called Helia which isn't compatible with Kubo's RPC API.

As such we should remove js-ipfs and refactor our code our the Kubo RPC API and simplify the IPFS deploy drastically.

## To Do

- [ ] Remove js-ipfs deps
- [ ] Replace js-ipfs-http-api with the kubo-rpc API
- [ ] Remove unnecessary options for js-ipfs nodes from config
- [ ] Test!
- [ ] Release!
