### ISSUE TITLE
Plan Timeline for Milestone 2

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#86]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Now that we have a clear picture of what we're doing for the next milestone, we should make a more concrete timeline for everything.

Ideally we should aim to have something working before the presentation at the FFDW meeting in October

...

## To Do

- [ ] Write up steps
- [ ] Estimate weeks
- [ ] Review with group
- [ ] Settle on dates

**Comment by RangerMauve** [comment]
tl;dr we're releasing in September
