### ISSUE TITLE
implement social  ActivityPub inbox

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#87]
🎟️ **Re-ticketed from:** #80 
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

 now that we have a more clear picture of what we need to do for the social side of things, we should start implementing the inbox and the moderation queue

we will be using the inbox code in this blog post as inspiration: https://paul.kinlan.me/adding-activity-pub-to-your-static-site/

## To Do

- [x] Set up a new repository `social.distributed.press` with Fastify and Typescript (3h)
- [x] sketch up data store apis (leveldb)
- [x] sketch up http apis
- [x] implement store apis with tests
- [x] Implement blocklist/allowlist http apis
- [x] choose http signatures apis
- [x] make utility to generate keypairs
- [x] add auth handlers to all http apis using signatures
- [x] use allow list and blocklist for incoming requests
- [x] properly respond to inbox requests
- [x] add items to moderation queue
- [x] handle follow requests, use allow'blocklists and moderation queue. Send follo accepts
- [ ] handle replies
- [x] implement webhook registration for listening on new updates
- [x] implement POST for the outbox
- [x] Find typescript library with ActivityPub related types or stub them out ourselves (2h)
- [ ] Fix follower approval issue

**Comment by RangerMauve** [comment]
updated the todo list

**Comment by maisutton** [comment]
When I created a new blog on Sutty and had it create a Fediverse account, I noticed that it required an approval for new followers.

**Comment by RangerMauve** [comment]
We'll track the replies thing as a separate issue
