### ISSUE TITLE
Improve startup and initial site sync

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#88]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

At the moment the first thing we do in DP before enavbling the HTTP server is an initial sync of all the sites. This is there so that we can account for any changes made manually .

We block initializing the HTTP API until this is done to avoid race conditions with data being updated by both the initial sync and an HTTP API call.

This leads to ever increasing initial load times and slow reboots.

One thing we can do to improve things is to be able to start the HTTP API right away and  have "locks" on individual domains.

This will also help address any race conditions of multiple API calls going to the same site.

## To Do

- [ ] Add a `mutexMap` to the `sites` config which maps from domain to a [mutex](https://www.npmjs.com/package/async-mutex) instance.
- [ ] Add a `runExclusive(domain, cb)` method which will auto-create a mutex for the domain if one doesn't exist, and then run the cb on that mutex
- [ ] Have `sync` and `unsync` use this method so that they can only run exclusively
- [ ] In server initializing, run the initial site sync after the HTTP API is initialized
- [ ] Test that it's working!
