### ISSUE TITLE
Social Inbox: Implement allowlist and blocklist apis

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#89]
🎟️ **Re-ticketed from:** #87 
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

As part of our moderation strategy our social inbox will automatically block incoming activities from some instances/users and automatically allow activities from others.

This is facilitated by storing lists of users or instances in our db and checking them for incoming AP inbox requests. We have "global" lists for the whole instance, and domain-specific ones so publishers can add / exclude filters themselves. 

We need to implement the HTTP apis for adding/removing items in bulk, and a new API for reusing the moderation filter info

## To Do

- [ ] implement `GET/POST/DELETE /blocklist` in api/index.js: use the `store.blocklist` methods
- [ ] Same for `/allowlist`
- [ ] Implement `GET/POST/DELETE /:domain/blocklist`: Use `store.forDomain(domain).blocklist` methods
- [ ] Same for `/:domain/allowlist`
- [ ] Implement new class named `ModerationChecker` in `api/moderation.ts`
  - [ ] Take store in constructor and save it as a private property
  - [ ]  Add `async isAllowed(pattern:string, domain: string) : Promise<boolean>` method
  - [ ] If in global blocklist, deny
  - [ ] if in domain blocklist deny
  - [ ] if in global allow list accept
  - [ ] if in domain allow list accept
