### ISSUE TITLE
Set up resource library

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/distributed-press-organizing#9]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Set up a space for resource library.  

## Task Summary

Decide on a place to put permanent resources, like a handbook or wiki, that is publicly facing. This may be on a website.

## To Do

- [x] Decide on a place for resource library
- [x] Set up resource library
- [ ] Document in wiki
  - [x] Intro and background on projects
  - [x] Who's involved
  - [x] Contributor involvement 
  - Tools from #2 
    - [x] Chat
    - [ ] GH repo
    - [ ] Calendar
    - [x] Mail
    - [ ] Mailing list
  - Community guidelines
    - [ ] Decision making
    - [ ] CoC
    - [ ] Values
  - [x] Glossary of terms

**Comment by uditvira** [comment]
We've decided to use Github's Wiki feature for our resource library. Work in progress [here](https://github.com/hyphacoop/distributed-press-organizing/wiki).
