### ISSUE TITLE
Social Inbox: Implement store apis

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#90]
🎟️ **Re-ticketed from:** #87   
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

I've stubbed out the apis for store/index.js but a bunch of them aren't actually filled in. These methods should be filled in and some tests written to check that they work.

## To Do

- [ ] Finish apis in store/index.js, reference the leveldb docs or check out how the config stuff works in api.distributed.press
- [ ] Add basic tests to add/remove data from all the store types [e.g.](https://github.com/hyphacoop/api.distributed.press/blob/main/config/admin.ts#L13)
- [ ] Add test to make sure the `forDomain` method properly caches data [e.g.](https://github.com/hyphacoop/api.distributed.press/blob/main/config/admin.test.ts)
- [ ] Optionally split index.js into seperate files per store class
