### ISSUE TITLE
FFDW Milestone 2 + Annual Report Tasks

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#91]
📅 **Due date: 8 September 2023**

## Task Summary
All the writing/promotion/grant management tasks that need to be done to complete milestone 2 and submit our annual report to FFDW.

## To Do
* [x] aug 25: get partner sign off (intention to use DP) - mai/mauve
- NOTE: if they sign off on public announcement, announce in press release, if it's someone we are in private conversation we include in grant report
* [x] aug 28: ffdw case study draft - mai
* [x] aug 30: email ffdw case study draft to sofia - mai
* [ ] aug 30: feature complete
* [ ] aug 30: sutty demo video recording script - fauno
* [ ] aug 30: press release draft (without demo video) - mai
* [x] sep 01: first draft of milestone report - mai
* [ ] sep 01: demo recording - sutty
* [x] sep 01: product strategy & fundraising plan - ben
* [x] sep 07: submit annual report - mai + team

technical deliverables tracked on github*: https://github.com/hyphacoop/distributed-press-organizing/issues/87
