### ISSUE TITLE
Social Inbox: Webhooks

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#93]
🎟️ **Re-ticketed from:** #87 
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

In order notify publishers of newly queued moderation items, they should register "webhooks" which describe API endpoints they expect requests to go to.

## To Do

- [x] New interface called `Hook` which tracks a url, method, and headers (`[name:string]:string`)
- [x] new HookStore with methods for tracking the `moderationqueued`, `onapproved` (formerly onnew), and `onrejected` hooks. Each type should be a different `key`.
- [x] Implement `get/set/delete{ModerationQueued/OnApproved/OnRejected}(hook:Hook)` methods which will interact with the db
- [x] Add under the ActorStore with the name `hooks`
- [x] Create new `HookSystem` which takes the store, and `fetch` as parameters (similar to ActivityPubSystem)
- [ ] Add methods for `dispatch{ModerationQueued/OnApproved/OnRejected}(actor: string, activity: APActivity) : Promise<boolean>` which will attempt to fecth the webhook type and perform a signed `fetch` with the body set to the `activity` and the url/etc taken from the hook definition. If the hook doesn't exist, return false, on success return true. If the method is GET, don't set the body for the request
- [ ] Write test with a mocked `fetch` API to make sure the hook gets triggered with the expected parameters
- [ ] Add http APIs with proper schemas to register hooks
- [ ] Pass hook system into the apsystem and have it dispatch the hooks where appropriate. (when accepting, when denying, when queued)
- [ ] Add tests to AP system to check the hook are being invoked

**Comment by RangerMauve** [comment]
Finished and merged
