### ISSUE TITLE
Add more robust OOM crash detection code for IPFS

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#94]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

Our current code for tracking OOM crashes of Kubo are sometimes missing the process crashing. We should add more robustness to the crash detection logic.

Currently this means we need manual restarts every now and then when kubo gets into this state.

...

## To Do

- [ ] Look at the ipfsd-ctl code to detect when OOM crashes happen
- [ ] fix up restart code [here](https://github.com/hyphacoop/api.distributed.press/blob/main/protocols/ipfs.ts#L123)
- [ ] Trigger OOM by running kubo on low resource VM
- [ ] Test restart logic
