### ISSUE TITLE
create a cron job to restart the service every few days

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#95]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

at the moment for reaching some sort of out of memory issues that are crushing the surface every week so. so instead of having to manually restart the surface.ically whenever the builds break we should just have it automatically restart until we figure out what the memory leak is.

https://github.com/hyphacoop/api.distributed.press/blob/main/ansible/roles/distributed_press/tasks/main.yml

so to that extent we need to add a new cron tab templates to the ansible and just have a do system ctl restarts api.distributed.press
...

## To Do

- [ ] add ansible task for enabling crontab
- [ ] deploy to staging
- [ ] test that it works
- [ ] deploy to production
