### ISSUE TITLE
Track replies to posts

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#96]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

so now that we can receive replies and the inbox we should start storing them in a collection so that the front end can pull replies for a post and render them in the html if they want or similar

so for that we need a new store to store replies I think the way it'll work is will have the URL of the reply prefix in the store and we'll have something similar to how we have the actorthe store where we can like cash them in memory and low generate them on the fly per actor id except this will be under an actor and the post your else will be part of the prefix and then we'll have http eyes to I get and delete and will use the moderation queue to automatically add or remove things from the replies and see also when we manually approve of reply will add it to then you will also needs the http I to get the list.

...

## To Do

- [ ] Add RepliesStore class which can track activitystoes per reply url (by adding reply as a prefix in sublevel)
- [ ] Add the reply store to the actor store
- [ ] add logic to inbox to add accepted or auto accepted replies to the appropriate reply store
- [ ] add new http path to get the list of replies or delete items in that list
- [ ] add unit tests for new apis
- [ ] deploy to staging and test with mastodon
- [ ] coordinate with sutty on integration path

**Comment by fauno** [comment]
I can't seem to parse the longer description!  But I would expect to find replies by fetching an OrderedCollection somewhere, not sure if the AP spec has one for those.  The client should add replies to activities too, but not sure if it should issue an Update activity for this.

**Comment by fauno** [comment]
Is it a GET for the inbox?

> The inbox stream contains all activities received by the actor. The server SHOULD filter content according to the requester's permission. In general, the owner of an inbox is likely to be able to access all of their inbox contents. Depending on access control, some other content may be public, whereas other content may require authentication for non-owner users, if they can access the inbox at all.  -- https://www.w3.org/TR/activitypub/#inbox
