### ISSUE TITLE
Add HTML snippet for "Published With Distributed.Press"

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#98]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

It'd be useful to have a 1990's style marketing thing where we can give folks an HTML snippet to copy into their templates 

## To Do

- [ ] Sketch up design based on DP logo
- [ ] HTML snippet: `<a>` tag linking to distributed.press wrapping an `<img>` tag with alt text describing the image contents.
- [ ] Add to docs somewhere prominant

**Comment by RangerMauve** [comment]
duplicate of #131
