### ISSUE TITLE
Update docs.distributed.press

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#99]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** 2 Dec 2023  
🎯 **Success criteria:**   

## Task Summary

...

## To Do

- [ ] Docs on the new CLI
- [ ] Docs on create-repo tool
- [ ] Docs on using API to get a token
- [ ] Update reader docs

**Comment by RangerMauve** [comment]
- [ ] self deploying dogs need social inbox update
- [ ] need new page describing social inbox
  - [ ] Mention how to use it with sutty
- [ ] self deployment docs need to mention dns better
- [ ] mention that you should use a specific version of been to or debbie in to self deploy
- [ ] talk about moderation in docs
- [ ] Update approach with next "phase"
- [ ] Add akhi's browser to access on protocols page
- [ ] Talk about account creation in self hosting guide
- [ ] Review sutty cms section (add socia inbox info there)

**Comment by RangerMauve** [comment]
https://github.com/p2plabsxyz/peersky-browser

**Comment by RangerMauve** [comment]
https://github.com/hyphacoop/docs.distributed.press/

**Comment by RangerMauve** [comment]
Do PRS into this branch: https://github.com/hyphacoop/docs.distributed.press/tree/social-inbox

**Comment by RangerMauve** [comment]
Once we publish we should have the root of the social inbox redirect to docs.distributed.press/social (or similar)

**Comment by sutty-coop** [comment]
Review of updates needed:

- in distributed.press I suggest to re-arrange the content, in order to begin the page with a **clear definition of the mission / promise of DP**, and carry the Compost info and screenshot below, after the list of projects using DP. I have prepared a draft version of the home with this small changes.

Draft of the update (fonts in the plain text are different, because this is a screenshot in the panel view, not published yet):


![Image](https://github.com/hyphacoop/distributed-press-organizing/assets/113475467/c7a0f37b-3aea-4406-9eb7-e477df08233b)

**Comment by maisutton** [comment]
Good idea to add the concise description at the top. Just made a few edits to the text but I think it looks ready to publish!

**Comment by sutty-coop** [comment]
@akhileshthite do you have time to review the https://docs.distributed.press/ and assign yourself the updating of some of this documentation?

**Comment by akhileshthite** [comment]
> [@akhileshthite](https://github.com/akhileshthite) do you have time to review the https://docs.distributed.press/ and assign yourself the updating of some of this documentation?

We need to have social reader there.
Yeah, will do that next week.

**Comment by AnaFukelman** [comment]
Update for Milestone 5:
Documentation will be updated to include index mentions.

**Comment by AnaFukelman** [comment]
- [ ]  Pending: update documentation with the news on EXPLORE and uncensorable front ends
